In [1]:
import tensorflow as tf
import tensorflow.contrib.slim as slim
import numpy as np

In [2]:
class contextual_bandit():
    def __init__(self):
        self.state = 0
        #List out our bandits. Currently arms 4, 2, and 1 (respectively) are the most optimal.
        self.bandits = np.array([[0.2,0,-0.0,-5],[0.1,-5,1,0.25],[-5,5,5,5]])
        self.num_bandits = self.bandits.shape[0]
        self.num_actions = self.bandits.shape[1]
        
    def getBandit(self):
        self.state = np.random.randint(0,len(self.bandits)) #Returns a random state for each episode.
        return self.state
        
    def pullArm(self,action):
        #Get a random number.
        bandit = self.bandits[self.state,action]
        result = np.random.randn(1)
        if result > bandit:
            #return a positive reward.
            return 1
        else:
            #return a negative reward.
            return -1

In [3]:
class agent():
    # defined for one bandit, not 3
    def __init__(self, lr, s_size,a_size):
        #These lines established the feed-forward part of the network. The agent takes a state and produces an action.
        self.state_in= tf.placeholder(shape=[1],dtype=tf.int32)
        state_in_OH = slim.one_hot_encoding(self.state_in,s_size)
        output = slim.fully_connected(state_in_OH,a_size,\
            biases_initializer=None,activation_fn=tf.nn.sigmoid,weights_initializer=tf.ones_initializer())
        self.output = tf.reshape(output,[-1])
        self.chosen_action = tf.argmax(self.output,0)

        #The next six lines establish the training proceedure. We feed the reward and chosen action into the network
        #to compute the loss, and use it to update the network.
        self.reward_holder = tf.placeholder(shape=[1],dtype=tf.float32)
        self.action_holder = tf.placeholder(shape=[1],dtype=tf.int32)
        self.responsible_weight = tf.slice(self.output,self.action_holder,[1])
        self.loss = -(tf.log(self.responsible_weight)*self.reward_holder)
        optimizer = tf.train.GradientDescentOptimizer(learning_rate=lr)
        self.update = optimizer.minimize(self.loss)

In [11]:
tf.reset_default_graph() #Clear the Tensorflow graph.

cBandit = contextual_bandit() #Load the bandits.
myAgent = agent(lr=0.001,s_size=cBandit.num_bandits,a_size=cBandit.num_actions) #Load the agent.
weights = tf.trainable_variables()[0] #The weights we will evaluate to look into the network.

total_episodes = 10000 #Set total number of episodes to train agent on.
total_reward = np.zeros([cBandit.num_bandits,cBandit.num_actions]) #Set scoreboard for bandits to 0.
e = 0.1 #Set the chance of taking a random action.

init = tf.global_variables_initializer()

# Launch the tensorflow graph
with tf.Session() as sess:
    sess.run(init)
    i = 0
    while i < total_episodes:
        s = cBandit.getBandit() #Get a state from the environment.
        
        #Choose either a random action or one from our network.
        if np.random.rand(1) < e:
            action = np.random.randint(cBandit.num_actions)
        else:
            output, action = sess.run([myAgent.output, myAgent.chosen_action], feed_dict={myAgent.state_in:[s]})
            print(output, action)
        
        reward = cBandit.pullArm(action) #Get our reward for taking an action given a bandit.
        
        #Update the network.
        feed_dict={myAgent.reward_holder:[reward],myAgent.action_holder:[action],myAgent.state_in:[s]}
        _,ww = sess.run([myAgent.update,weights], feed_dict=feed_dict)
        
        #Update our running tally of scores.
        total_reward[s,action] += reward
        if i % 500 == 0:
            print ("Mean reward for each of the " + str(cBandit.num_bandits) + " bandits: " + str(np.mean(total_reward,axis=1)))        
        i+=1
        # print(ww)
for a in range(cBandit.num_bandits):
    print ("The agent thinks action " + str(np.argmax(ww[a])+1) + " for bandit " + str(a+1) + " is the most promising....")
    if np.argmax(ww[a]) == np.argmin(cBandit.bandits[a]):
        print ("...and it was right!")
    else:
        print ("...and it was wrong!")

[0.7310586 0.7310586 0.7310586 0.7310586] 0
Mean reward for each of the 3 bandits: [-0.25  0.    0.  ]
[0.7310586 0.7310586 0.7310586 0.7310586] 0
[0.7311114 0.7310586 0.7310586 0.7310586] 0
[0.7310586 0.7310586 0.7310586 0.7310586] 0
[0.7310057 0.7310586 0.7310586 0.7310586] 1
[0.7310057 0.7310586 0.7310586 0.7310586] 1
[0.73116434 0.7310586  0.7310586  0.7310586 ] 0
[0.7309528 0.7310057 0.7310586 0.7310586] 2
[0.7309528 0.7310057 0.7311114 0.7310586] 2
[0.73121715 0.7310586  0.7310586  0.7310586 ] 0
[0.7310057 0.7311114 0.7310586 0.7310586] 1
[0.7310057  0.73116434 0.7310586  0.7310586 ] 1
[0.73132277 0.7310586  0.7310586  0.7310586 ] 0
[0.7310057  0.73121715 0.7310586  0.7310586 ] 1
[0.7310057 0.73127   0.7310586 0.7310586] 1
[0.7313756 0.7310586 0.7310586 0.7310057] 0
[0.7310057  0.73132277 0.7310586  0.7310586 ] 1
[0.7309528  0.7310057  0.73116434 0.7310586 ] 2
[0.7309528  0.7310057  0.73121715 0.7310586 ] 2
[0.7309528 0.7310057 0.73127   0.7310586] 2
[0.7309528  0.7310057  0.7313

[0.7342531 0.7310586 0.7308999 0.7309528] 0
[0.7308999  0.7310057  0.7314813  0.73116434] 2
[0.7343049 0.7310586 0.7308999 0.7309528] 0
[0.73435676 0.7310586  0.7308999  0.7309528 ] 0
[0.7310586  0.73477083 0.7310057  0.7310586 ] 1
[0.73440856 0.7310586  0.7308999  0.7309528 ] 0
[0.7310586 0.7348225 0.7310057 0.7310586] 1
[0.7310586 0.7348742 0.7310057 0.7310586] 1
[0.73084694 0.7310057  0.73142856 0.73116434] 2
[0.7310586 0.7349258 0.7310057 0.7310586] 1
[0.73084694 0.7310057  0.7313758  0.73116434] 2
[0.73446035 0.7310586  0.7308999  0.7309528 ] 0
[0.7310586 0.7349775 0.7310057 0.7310586] 1
[0.7345122 0.7310586 0.7308999 0.7309528] 0
[0.73084694 0.7309528  0.73142856 0.73116434] 2
[0.7310586 0.7350291 0.7310057 0.7310586] 1
[0.73084694 0.7309528  0.7314814  0.73116434] 2
[0.7310586 0.7350807 0.7310057 0.7310586] 1
[0.7345639 0.7310586 0.7308999 0.7309528] 0
[0.7310586 0.7351322 0.7310057 0.7310586] 1
[0.7346157 0.7310586 0.7308999 0.7309528] 0
[0.7346674 0.7310586 0.7308999 0.7309528

[0.73111147 0.7374876  0.73079395 0.7311114 ] 1
[0.73084694 0.73084694 0.7312704  0.7334212 ] 3
[0.73111147 0.7375384  0.73079395 0.7311114 ] 1
[0.73111147 0.73758924 0.73079395 0.7311114 ] 1
[0.73111147 0.7376908  0.73079395 0.7311114 ] 1
[0.73084694 0.73084694 0.7312704  0.7334733 ] 3
[0.73111147 0.73774153 0.73079395 0.7311114 ] 1
[0.73084694 0.73084694 0.7312704  0.7335254 ] 3
[0.7376908 0.7310057 0.730741  0.7308999] 0
[0.73111147 0.73779225 0.73079395 0.7311114 ] 1
[0.73774153 0.7310057  0.730741   0.7308999 ] 0
[0.73084694 0.73084694 0.7312704  0.7335775 ] 3
[0.73111147 0.73784304 0.73079395 0.7311114 ] 1
[0.73779225 0.7310057  0.730741   0.7308999 ] 0
[0.73111147 0.7378937  0.73079395 0.7311114 ] 1
[0.73084694 0.73084694 0.7312704  0.7336296 ] 3
[0.73784304 0.7310057  0.730741   0.7308999 ] 0
[0.7378937 0.7310057 0.730741  0.7308999] 0
[0.73084694 0.73084694 0.7312704  0.7336816 ] 3
[0.73084694 0.73084694 0.7312704  0.73373365] 3
[0.7379444 0.7310057 0.730741  0.7308999] 0
[0.7

[0.73084694 0.7308999  0.73121756 0.7367744 ] 3
[0.7311644 0.7404585 0.730741  0.7310586] 1
[0.7410062  0.7309528  0.73068804 0.7308999 ] 0
[0.7311644 0.7405083 0.730741  0.7310586] 1
[0.7311644  0.74055815 0.730741   0.7310586 ] 1
[0.73084694 0.7308999  0.73121756 0.7368254 ] 3
[0.73084694 0.7308999  0.73121756 0.7368765 ] 3
[0.7311644  0.74060804 0.730741   0.7310586 ] 1
[0.74110556 0.7309528  0.73068804 0.7308999 ] 0
[0.74115527 0.7309528  0.73068804 0.7308999 ] 0
[0.7311644  0.74065787 0.730741   0.7310586 ] 1
[0.73084694 0.7308999  0.73121756 0.7369275 ] 3
[0.73084694 0.7308999  0.73121756 0.73697853] 3
[0.73084694 0.7308999  0.73121756 0.73702943] 3
[0.7412049  0.7309528  0.73068804 0.7308999 ] 0
[0.7311644  0.74070764 0.730741   0.7310586 ] 1
[0.73084694 0.7308999  0.73121756 0.73708045] 3
[0.73084694 0.7308999  0.73121756 0.73713136] 3
[0.7311644  0.74075747 0.730741   0.7310586 ] 1
[0.73084694 0.7308999  0.73121756 0.7371823 ] 3
[0.74125457 0.7309528  0.73068804 0.7308999 ] 0


[0.73084694 0.7311644  0.7311647  0.7398587 ] 3
[0.73084694 0.7311644  0.7311647  0.73990875] 3
[0.74444765 0.7309528  0.73058206 0.7308999 ] 0
[0.73084694 0.7311644  0.7311647  0.7399588 ] 3
[0.7444963  0.7308999  0.73058206 0.7308999 ] 0
[0.73111147 0.7437655  0.73068804 0.7308999 ] 1
[0.73084694 0.7311644  0.7311647  0.7400588 ] 3
[0.73084694 0.7311644  0.7311647  0.7401089 ] 3
[0.73111147 0.7438143  0.73068804 0.7308999 ] 1
[0.74454486 0.7308999  0.73058206 0.73084694] 0
[0.73084694 0.7311644  0.7311647  0.74015886] 3
[0.73084694 0.7311644  0.7311647  0.7402088 ] 3
[0.7445935  0.7308999  0.73058206 0.73084694] 0
[0.73084694 0.7311644  0.7311647  0.74025875] 3
[0.73111147 0.7438631  0.73068804 0.7308999 ] 1
[0.73084694 0.7311644  0.7311647  0.7403087 ] 3
[0.7446421  0.7308999  0.73058206 0.73084694] 0
[0.73111147 0.7439119  0.730741   0.7308999 ] 1
[0.7446906  0.7308999  0.73058206 0.73084694] 0
[0.73111147 0.7439607  0.730741   0.7308999 ] 1
[0.73111147 0.74400944 0.730741   0.7308

[0.7476236  0.73084694 0.73052907 0.730741  ] 0
[0.73089993 0.73111147 0.7311647  0.74347216] 3
[0.73089993 0.73111147 0.7311647  0.74352103] 3
[0.7312172  0.7470033  0.73063505 0.73079395] 1
[0.74767125 0.73084694 0.73052907 0.730741  ] 0
[0.7312172  0.74705106 0.73063505 0.73079395] 1
[0.73089993 0.73111147 0.7311647  0.7435699 ] 3
[0.7477188  0.73084694 0.73052907 0.730741  ] 0
[0.73089993 0.73111147 0.7311647  0.74361885] 3
[0.73089993 0.73111147 0.7311647  0.7436678 ] 3
[0.73089993 0.73111147 0.7311647  0.7437166 ] 3
[0.7477664  0.73084694 0.73052907 0.730741  ] 0
[0.747814   0.73084694 0.73052907 0.730741  ] 0
[0.7312172  0.7470989  0.73063505 0.73079395] 1
[0.7312172  0.74714667 0.73063505 0.73079395] 1
[0.7312172  0.7471944  0.73063505 0.73079395] 1
[0.73089993 0.73111147 0.7311119  0.7437655 ] 3
[0.7478615  0.73084694 0.73052907 0.730741  ] 0
[0.74790907 0.73084694 0.73052907 0.730741  ] 0
[0.73089993 0.73111147 0.7311119  0.7438143 ] 3
[0.73089993 0.73111147 0.7311119  0.7438

[0.73095286 0.73105866 0.7311119  0.7465244 ] 3
[0.73095286 0.73105866 0.7311119  0.7465724 ] 3
[0.750921   0.73079395 0.73047596 0.73058206] 0
[0.73095286 0.73105866 0.7311119  0.7466203 ] 3
[0.73095286 0.73105866 0.7311119  0.74666816] 3
[0.7312172  0.75045437 0.7305821  0.73079395] 1
[0.7312172  0.7505011  0.7305821  0.73079395] 1
[0.7509676  0.73079395 0.73047596 0.73058206] 0
[0.7510142  0.73079395 0.73047596 0.73058206] 0
[0.7510607  0.73079395 0.73047596 0.73058206] 0
[0.7312172  0.7505478  0.73052907 0.73079395] 1
[0.7511073  0.73079395 0.73047596 0.73058206] 0
[0.7511538  0.73079395 0.73047596 0.73058206] 0
[0.73095286 0.7310057  0.7311119  0.7467161 ] 3
[0.73095286 0.7310057  0.7311119  0.74676406] 3
[0.7512003  0.73079395 0.73047596 0.73058206] 0
[0.7512468  0.73079395 0.73047596 0.73058206] 0
[0.73095286 0.7310057  0.7311119  0.7468119 ] 3
[0.7512933  0.73079395 0.73047596 0.73058206] 0
[0.73095286 0.7310057  0.7311119  0.7468598 ] 3
[0.75133973 0.73079395 0.73047596 0.7305

[0.73095286 0.7311644  0.73127043 0.7495637 ] 3
[0.7541472  0.73079395 0.73036975 0.73036975] 0
[0.7541927  0.73079395 0.73036975 0.73036975] 0
[0.7312701  0.7536448  0.73052907 0.73068804] 1
[0.73095286 0.7311644  0.73127043 0.7496107 ] 3
[0.7542383  0.73079395 0.73036975 0.73036975] 0
[0.73095286 0.7311644  0.73127043 0.7496577 ] 3
[0.75428385 0.73079395 0.73036975 0.73036975] 0
[0.7543294  0.73079395 0.73036975 0.73036975] 0
[0.73095286 0.7311644  0.73127043 0.7497047 ] 3
[0.75437486 0.73079395 0.73036975 0.73036975] 0
[0.7312701  0.75373626 0.73052907 0.73068804] 1
[0.7544204  0.730741   0.73036975 0.73036975] 0
[0.7312701  0.753782   0.73052907 0.730741  ] 1
[0.75446594 0.730741   0.73036975 0.73036975] 0
[0.7312701  0.7538277  0.73052907 0.730741  ] 1
[0.7545114  0.730741   0.73036975 0.73036975] 0
[0.73095286 0.7311644  0.73127043 0.7497986 ] 3
[0.7312701  0.75387335 0.73052907 0.730741  ] 1
[0.7545569  0.730741   0.73036975 0.73036975] 0
[0.73095286 0.7311644  0.73127043 0.7498

[0.7310058  0.7312172  0.7312176  0.75295705] 3
[0.7310058 0.7312172 0.7312176 0.753003 ] 3
[0.7313228  0.7567228  0.73031676 0.73068804] 1
[0.7313228  0.7567676  0.73031676 0.73068804] 1
[0.75717    0.73063505 0.7302636  0.7302104 ] 0
[0.75721467 0.73063505 0.7302636  0.7302104 ] 0
[0.7572593  0.73063505 0.7302636  0.7302104 ] 0
[0.7313228  0.75681233 0.73031676 0.73068804] 1
[0.7310058 0.7312172 0.7312176 0.7530489] 3
[0.7310058 0.7312172 0.7312176 0.7530949] 3
[0.7310058 0.7312172 0.7312176 0.7531408] 3
[0.75730395 0.73063505 0.7302636  0.7302104 ] 0
[0.7310058 0.7312172 0.7312176 0.7531867] 3
[0.75734854 0.73063505 0.7302636  0.7302104 ] 0
[0.7313228  0.75685716 0.73031676 0.73068804] 1
[0.7310058  0.7312172  0.7312176  0.75323254] 3
[0.7313228  0.75690186 0.73031676 0.73068804] 1
[0.7310058  0.7312172  0.73116475 0.75327843] 3
[0.7313228  0.7569466  0.73031676 0.73068804] 1
[0.7310058  0.7312172  0.73116475 0.7533243 ] 3
[0.7313228  0.75699127 0.73031676 0.73068804] 1
[0.7310058  

[0.73137563 0.7597368  0.73031676 0.7306881 ] 1
[0.73137563 0.7597807  0.73031676 0.7306881 ] 1
[0.7310058 0.7311644 0.7312176 0.7561843] 3
[0.7310058 0.7311644 0.7312176 0.7562293] 3
[0.7598684  0.73052907 0.7299445  0.7301573 ] 0
[0.75991213 0.73052907 0.7299445  0.7301573 ] 0
[0.75995594 0.73052907 0.7299445  0.7301573 ] 0
[0.7313228  0.7598245  0.73031676 0.7306881 ] 1
[0.75999975 0.73052907 0.7299445  0.7301573 ] 0
[0.7600435  0.73052907 0.7299445  0.7301573 ] 0
[0.7600873  0.73052907 0.7299445  0.7301573 ] 0
[0.7310058 0.7311644 0.7312176 0.7562742] 3
[0.76013106 0.73052907 0.72989124 0.7301573 ] 0
[0.7310058  0.7311644  0.7312176  0.75631917] 3
[0.7601748  0.73052907 0.72989124 0.7301573 ] 0
[0.7313228  0.7598684  0.73031676 0.7306881 ] 1
[0.7602185  0.73052907 0.72989124 0.7301573 ] 0
[0.76026213 0.73052907 0.72989124 0.7301573 ] 0
[0.7603058  0.73052907 0.72989124 0.7301573 ] 0
[0.7310058  0.7311644  0.7312176  0.75636405] 3
[0.7603495  0.73052907 0.72989124 0.7301573 ] 0
[0.7

[0.73095286 0.7311115  0.73116475 0.7593415 ] 3
[0.73095286 0.7311115  0.73116475 0.75938547] 3
[0.76316017 0.73047596 0.7297848  0.7300509 ] 0
[0.76320297 0.73047596 0.7297848  0.7300509 ] 0
[0.73095286 0.7311115  0.73116475 0.7594295 ] 3
[0.73095286 0.7311115  0.73116475 0.75947344] 3
[0.76324576 0.73047596 0.7297848  0.7300509 ] 0
[0.7632885  0.73047596 0.7297848  0.7300509 ] 0
[0.7633313  0.73047596 0.7297848  0.7300509 ] 0
[0.7313228  0.7623013  0.73031676 0.7307411 ] 1
[0.7313228  0.76234436 0.73031676 0.7307411 ] 1
[0.73095286 0.7311115  0.73116475 0.7595174 ] 3
[0.7633741  0.73047596 0.7297848  0.7300509 ] 0
[0.73095286 0.7311115  0.73116475 0.75956124] 3
[0.73095286 0.7311115  0.73116475 0.75960517] 3
[0.7634168  0.73047596 0.7297848  0.7300509 ] 0
[0.73095286 0.7311115  0.73116475 0.7596491 ] 3
[0.73095286 0.7311115  0.73116475 0.75969297] 3
[0.7313228  0.76238745 0.73031676 0.7307411 ] 1
[0.76345956 0.73047596 0.7297848  0.7300509 ] 0
[0.73095286 0.7311115  0.73116475 0.7597

[0.7313228  0.7644387  0.73036987 0.7306351 ] 1
[0.7665855  0.73031676 0.7297848  0.7299445 ] 0
[0.7311644  0.7310587  0.7312176  0.76251656] 3
[0.76662725 0.73031676 0.7297848  0.7299445 ] 0
[0.7311644  0.7310587  0.7312176  0.76255953] 3
[0.7311644 0.7310587 0.7312176 0.7626025] 3
[0.76666903 0.73031676 0.7297848  0.7299445 ] 0
[0.7313228  0.76448107 0.73031676 0.7306351 ] 1
[0.7313228  0.7645235  0.73031676 0.7306351 ] 1
[0.7311644  0.7310587  0.7312176  0.76264554] 3
[0.7313228  0.7645659  0.73031676 0.7306351 ] 1
[0.7313228  0.7646083  0.73031676 0.7306351 ] 1
[0.7311644  0.7310587  0.7312176  0.76268846] 3
[0.7313228  0.76465064 0.73031676 0.7306351 ] 1
[0.7311644  0.7310587  0.7312176  0.76273143] 3
[0.7311644  0.7310587  0.7312176  0.76277435] 3
[0.7313228  0.764693   0.73031676 0.7306351 ] 1
[0.7313228  0.76473534 0.73031676 0.7306351 ] 1
[0.7311644 0.7310587 0.7312176 0.7628173] 3
[0.7313228  0.7647777  0.73031676 0.7306351 ] 1
[0.7311644  0.7310587  0.7312176  0.76286024] 3


[0.7311115 0.7311115 0.7310591 0.7657055] 3
[0.73121727 0.767169   0.7302104  0.7306351 ] 1
[0.7311115  0.7311115  0.7310591  0.76574755] 3
[0.7311115  0.7311115  0.73111194 0.7657896 ] 3
[0.73121727 0.7672106  0.7302104  0.7306351 ] 1
[0.7311115  0.7311115  0.73111194 0.7658316 ] 3
[0.73121727 0.7672522  0.7302104  0.7306351 ] 1
[0.76935583 0.7299977  0.72973144 0.729838  ] 0
[0.73121727 0.76729375 0.7302104  0.7305821 ] 1
[0.7311115  0.7311115  0.73111194 0.7658736 ] 3
[0.7693967  0.7299977  0.72973144 0.729838  ] 0
[0.73121727 0.76733536 0.7302104  0.7305821 ] 1
[0.7694377  0.7299977  0.72973144 0.729838  ] 0
[0.73121727 0.76737684 0.7302104  0.7305821 ] 1
[0.7694786  0.7299977  0.72973144 0.729838  ] 0
[0.73121727 0.7674183  0.7302104  0.7305821 ] 1
[0.73121727 0.76745987 0.7302104  0.7305821 ] 1
[0.7311115  0.7311115  0.73111194 0.7659155 ] 3
[0.73121727 0.76750135 0.7302104  0.7305821 ] 1
[0.7311115  0.7311115  0.73111194 0.7659576 ] 3
[0.76951945 0.7299977  0.72973144 0.729838  

[0.7715079  0.729838   0.72962487 0.72967815] 0
[0.73116446 0.7311115  0.7312176  0.7683699 ] 3
[0.77154815 0.729838   0.72962487 0.72967815] 0
[0.77158844 0.729838   0.72962487 0.72967815] 0
[0.73121727 0.7704159  0.7301573  0.7305821 ] 1
[0.73116446 0.7311115  0.7312176  0.76841116] 3
[0.73116446 0.7311115  0.7312176  0.76845235] 3
[0.73116446 0.7311115  0.7312176  0.76849353] 3
[0.73121727 0.7704565  0.7301573  0.7305821 ] 1
[0.73116446 0.7311115  0.7312176  0.7685347 ] 3
[0.77162874 0.729838   0.72962487 0.72967815] 0
[0.73116446 0.7311115  0.7312176  0.7685759 ] 3
[0.73121727 0.7704971  0.7301573  0.7305821 ] 1
[0.771669   0.729838   0.72962487 0.72967815] 0
[0.73116446 0.7311115  0.7312176  0.76861703] 3
[0.77170914 0.729838   0.72962487 0.72967815] 0
[0.73116446 0.7311115  0.7312176  0.76865816] 3
[0.7717494  0.729838   0.72962487 0.72967815] 0
[0.73121727 0.7705377  0.7301573  0.7305821 ] 1
[0.73116446 0.7311115  0.7312176  0.7686993 ] 3
[0.7717896  0.729838   0.72962487 0.7296

[0.7740219  0.72962487 0.7295715  0.72962487] 0
[0.73121727 0.7310587  0.7312705  0.77126604] 3
[0.73121727 0.7310587  0.7312705  0.7713064 ] 3
[0.73121727 0.7310587  0.7312705  0.7713467 ] 3
[0.7740615  0.72962487 0.7295715  0.72962487] 0
[0.73121727 0.7731096  0.7301573  0.7305821 ] 1
[0.77410096 0.72962487 0.7295715  0.7295715 ] 0
[0.73121727 0.7310058  0.7312705  0.77138704] 3
[0.73121727 0.7310058  0.7312705  0.77142733] 3
[0.73121727 0.7310058  0.7312705  0.7714676 ] 3
[0.73121727 0.7310058  0.7312705  0.7715079 ] 3
[0.73121727 0.77314943 0.7301573  0.7305821 ] 1
[0.73121727 0.7310058  0.7312705  0.77154815] 3
[0.73121727 0.7731892  0.7301573  0.7305821 ] 1
[0.77418    0.72962487 0.7295715  0.7295715 ] 0
[0.73121727 0.7310058  0.7312705  0.77158844] 3
[0.77421945 0.72962487 0.7295715  0.7295715 ] 0
[0.73121727 0.77322894 0.7301573  0.7305821 ] 1
[0.73121727 0.7309529  0.7312705  0.77162874] 3
[0.73121727 0.77326876 0.7301573  0.7305821 ] 1
[0.774259   0.72962487 0.7295181  0.7295

[0.7312702  0.73100585 0.7312177  0.77366567] 3
[0.7312702  0.73100585 0.7312177  0.77370536] 3
[0.77683777 0.7294647  0.72941136 0.72930455] 0
[0.7768764  0.7294647  0.72941136 0.72930455] 0
[0.77691513 0.7294647  0.72941136 0.72930455] 0
[0.73127013 0.7757108  0.7301042  0.73052907] 1
[0.7312702  0.73100585 0.7312177  0.7737449 ] 3
[0.7312702  0.73100585 0.7312177  0.7737846 ] 3
[0.77695376 0.7294647  0.72941136 0.72930455] 0
[0.7312702  0.73100585 0.7312177  0.77382416] 3
[0.73127013 0.7757498  0.7301042  0.73052907] 1
[0.73127013 0.77578884 0.7301042  0.73052907] 1
[0.73127013 0.7758279  0.7301042  0.73052907] 1
[0.73127013 0.7758668  0.7301042  0.73052907] 1
[0.7769924  0.7294647  0.72941136 0.72930455] 0
[0.7312702  0.73100585 0.7312177  0.77386373] 3
[0.73127013 0.77590585 0.7301042  0.73052907] 1
[0.77703106 0.7294647  0.72941136 0.72930455] 0
[0.7312702  0.73100585 0.7312177  0.7739033 ] 3
[0.73127013 0.77594477 0.7301042  0.73052907] 1
[0.7770696  0.7294647  0.72941136 0.7292

[0.7311645  0.7309     0.73121774 0.77660537] 3
[0.7311645  0.7309     0.73121774 0.7766442 ] 3
[0.7312173 0.7786436 0.7299446 0.730476 ] 1
[0.7312173  0.77868176 0.7299446  0.730476  ] 1
[0.7789104  0.7293579  0.7293579  0.72914416] 0
[0.7311645  0.7309     0.73121774 0.77676034] 3
[0.7789484  0.7293579  0.7293579  0.72914416] 0
[0.7312173 0.7787199 0.7299446 0.730476 ] 1
[0.7789866  0.7293579  0.7293579  0.72914416] 0
[0.7311645  0.7309     0.73121774 0.7767991 ] 3
[0.7312173 0.778758  0.7299446 0.730476 ] 1
[0.7790246  0.7293579  0.7293579  0.72914416] 0
[0.7311645  0.7309     0.73121774 0.77683777] 3
[0.7790626  0.7293579  0.7293579  0.72914416] 0
[0.7311645  0.7309     0.73121774 0.7768764 ] 3
[0.7312702  0.77879614 0.7299446  0.730476  ] 1
[0.7311645  0.7309     0.73121774 0.77691513] 3
[0.77910066 0.7293579  0.7293579  0.72914416] 0
[0.7791386  0.7293579  0.7293579  0.72914416] 0
[0.77917665 0.7293579  0.7293579  0.72914416] 0
[0.7311645  0.7309     0.73121774 0.77695376] 3
[0.7

[0.7311645 0.7814738 0.7298381 0.730476 ] 1
[0.78121233 0.7292511  0.7292511  0.7290371 ] 0
[0.7812497 0.7292511 0.7292511 0.7290371] 0
[0.73095304 0.73100585 0.73121774 0.77917665] 3
[0.73095304 0.73100585 0.73121774 0.7792146 ] 3
[0.7311645 0.7815112 0.7298381 0.730476 ] 1
[0.78128713 0.7292511  0.7292511  0.7290371 ] 0
[0.7311645  0.78154844 0.7298381  0.730476  ] 1
[0.7309001  0.73100585 0.73121774 0.77925265] 3
[0.78132445 0.7292511  0.7292511  0.7290371 ] 0
[0.7309001  0.73100585 0.73121774 0.77929056] 3
[0.7311645  0.78158575 0.7298381  0.730476  ] 1
[0.7311645 0.781623  0.7298381 0.730476 ] 1
[0.7309001  0.73100585 0.73121774 0.7793286 ] 3
[0.7813618 0.7292511 0.7292511 0.7290371] 0
[0.7813992 0.7292511 0.7292511 0.7290371] 0
[0.78143656 0.7292511  0.7292511  0.7290371 ] 0
[0.7309001  0.73100585 0.73121774 0.77936655] 3
[0.7309001  0.73100585 0.73121774 0.77940446] 3
[0.7311645 0.7816603 0.7298381 0.730476 ] 1
[0.7814738 0.7292511 0.7292511 0.7290371] 0
[0.7311645 0.7816976 0.7

[0.7835835 0.7291976 0.7289836 0.7289836] 0
[0.7308471  0.7310587  0.73127055 0.78210676] 3
[0.7836202 0.7291976 0.7289836 0.7289836] 0
[0.7308471  0.7310587  0.73127055 0.7821439 ] 3
[0.7836569 0.7291976 0.7289836 0.7289836] 0
[0.78369355 0.72914416 0.7289836  0.7289836 ] 0
[0.7308471  0.7310587  0.73127055 0.78218096] 3
[0.7308471  0.7310587  0.73127055 0.7822181 ] 3
[0.73111165 0.7838035  0.72978485 0.7303699 ] 1
[0.73111165 0.7838402  0.72978485 0.7303699 ] 1
[0.73111165 0.7838768  0.72978485 0.7303699 ] 1
[0.73111165 0.78391343 0.72978485 0.7303699 ] 1
[0.7308471  0.7310587  0.73127055 0.7822552 ] 3
[0.73111165 0.78395003 0.72978485 0.7303699 ] 1
[0.7837302  0.72914416 0.7289836  0.7289836 ] 0
[0.78376687 0.72914416 0.7289836  0.7289836 ] 0
[0.7308471  0.7310587  0.73127055 0.7822923 ] 3
[0.7308471  0.7310587  0.73127055 0.7823294 ] 3
[0.7838402  0.72909063 0.7289836  0.7289836 ] 0
[0.73111165 0.7839866  0.72978485 0.7303699 ] 1
[0.7308471  0.7310587  0.73127055 0.7824035 ] 3
[0.7

[0.7312173  0.78605473 0.7297315  0.7303699 ] 1
[0.73079425 0.73090005 0.73127055 0.7847526 ] 3
[0.73079425 0.73090005 0.73127055 0.7847889 ] 3
[0.7312173 0.7860907 0.7297315 0.7303699] 1
[0.73079425 0.73090005 0.73127055 0.78482527] 3
[0.78630626 0.7290371  0.7288229  0.7288229 ] 0
[0.73079425 0.73090005 0.73127055 0.78486156] 3
[0.73079425 0.73090005 0.73127055 0.78489786] 3
[0.78634226 0.7290371  0.7288229  0.7288229 ] 0
[0.7863781 0.7290371 0.7288229 0.7288229] 0
[0.73079425 0.73090005 0.73127055 0.7849342 ] 3
[0.73079425 0.73090005 0.73127055 0.7849705 ] 3
[0.7312173 0.7861266 0.7297315 0.7303699] 1
[0.7312173 0.7861626 0.7297315 0.7303699] 1
[0.73079425 0.73090005 0.73127055 0.7850068 ] 3
[0.73079425 0.73090005 0.73127055 0.7850431 ] 3
[0.73079425 0.73090005 0.73127055 0.78507936] 3
[0.73079425 0.73090005 0.73127055 0.78511566] 3
[0.7312173  0.78619856 0.7297315  0.7303699 ] 1
[0.7864141 0.7290371 0.7288229 0.7288229] 0
[0.7312173 0.7862345 0.7297315 0.7303699] 1
[0.7312173 0.786

[0.73084724 0.730953   0.73127055 0.7874501 ] 3
[0.73084724 0.730953   0.73127055 0.7874857 ] 3
[0.7886891  0.7288229  0.72876924 0.7287157 ] 0
[0.7312702  0.78833634 0.7297315  0.7303699 ] 1
[0.73084724 0.730953   0.73127055 0.78752124] 3
[0.73084724 0.730953   0.73127055 0.7875568 ] 3
[0.73084724 0.730953   0.73127055 0.7875923 ] 3
[0.7887243  0.7288229  0.72876924 0.7287157 ] 0
[0.7887595  0.7288229  0.72876924 0.7287157 ] 0
[0.78879464 0.7288229  0.72876924 0.7287157 ] 0
[0.73084724 0.730953   0.73127055 0.7876279 ] 3
[0.7312702 0.7883717 0.7297315 0.7303699] 1
[0.73084724 0.730953   0.73127055 0.7876634 ] 3
[0.73084724 0.730953   0.73127055 0.78769886] 3
[0.7312702 0.788407  0.7297315 0.7303699] 1
[0.7312702  0.78844225 0.7297315  0.7303699 ] 1
[0.7312702  0.78847754 0.7297315  0.7303699 ] 1
[0.7888299  0.7288229  0.72876924 0.7287157 ] 0
[0.7312702 0.7885128 0.7297315 0.7303699] 1
[0.73084724 0.730953   0.73127055 0.7877344 ] 3
[0.73084724 0.730953   0.73127055 0.7877699 ] 3
[0.7

[0.7908533  0.72876924 0.72876924 0.7286084 ] 0
[0.7309001  0.730953   0.73127055 0.7900201 ] 3
[0.7312174  0.79068017 0.7297315  0.73042303] 1
[0.7908879  0.72876924 0.72876924 0.7286084 ] 0
[0.7312174  0.7907148  0.7297315  0.73042303] 1
[0.7309001  0.73100585 0.73127055 0.7900549 ] 3
[0.7312174  0.7907495  0.7297315  0.73042303] 1
[0.7312174  0.79078406 0.7297315  0.73042303] 1
[0.79092246 0.72876924 0.72876924 0.7286084 ] 0
[0.7312174  0.79081863 0.7297315  0.73042303] 1
[0.7309001  0.73100585 0.73127055 0.7900897 ] 3
[0.7309001  0.73100585 0.73127055 0.7901246 ] 3
[0.7309001  0.73100585 0.73127055 0.79015934] 3
[0.7309001  0.73100585 0.73127055 0.79019415] 3
[0.79095703 0.72876924 0.72876924 0.7286084 ] 0
[0.79099154 0.72876924 0.72876924 0.7286084 ] 0
[0.7312174  0.7908533  0.7297315  0.73042303] 1
[0.7910261  0.72876924 0.72876924 0.7286084 ] 0
[0.7312174  0.7908879  0.7297315  0.73042303] 1
[0.7910606  0.72876924 0.72876924 0.7286084 ] 0
[0.7309001  0.73100585 0.73127055 0.7902

[0.73079425 0.730953   0.73132336 0.7920581 ] 3
[0.73127025 0.7930133  0.7297315  0.7303699 ] 1
[0.79328483 0.7287157  0.728662   0.7286084 ] 0
[0.73079425 0.730953   0.73132336 0.7920923 ] 3
[0.73127025 0.79304725 0.7297315  0.7303699 ] 1
[0.73127025 0.7930812  0.7297315  0.7303699 ] 1
[0.73079425 0.730953   0.73132336 0.7921266 ] 3
[0.73127025 0.7931152  0.7297315  0.7303699 ] 1
[0.7933187 0.7287157 0.728662  0.7286084] 0
[0.73127025 0.79314905 0.7297315  0.7303699 ] 1
[0.73127025 0.793183   0.7297315  0.7303699 ] 1
[0.73079425 0.730953   0.73132336 0.79216087] 3
[0.7933526 0.7287157 0.728662  0.7286084] 0
[0.73079425 0.730953   0.73132336 0.792195  ] 3
[0.73127025 0.79321694 0.7297315  0.7303699 ] 1
[0.73127025 0.7932509  0.7297315  0.7303699 ] 1
[0.7933864 0.7287157 0.728662  0.7286084] 0
[0.73079425 0.730953   0.73132336 0.79222924] 3
[0.73127025 0.79328483 0.7297315  0.7303699 ] 1
[0.7934204 0.7287157 0.728662  0.7286084] 0
[0.7934542 0.7287157 0.728662  0.7286084] 0
[0.793488  0

[0.7957008 0.7286084 0.728662  0.7286084] 0
[0.795734  0.7286084 0.728662  0.7286084] 0
[0.73084724 0.7310059  0.7312178  0.79406196] 3
[0.73084724 0.7310059  0.7312178  0.79409564] 3
[0.73127025 0.79536813 0.72967815 0.7302637 ] 1
[0.79576725 0.7286084  0.728662   0.7286084 ] 0
[0.73084724 0.7310059  0.7312178  0.7941293 ] 3
[0.7958004 0.7286084 0.728662  0.7286084] 0
[0.73127025 0.7954015  0.72967815 0.7302637 ] 1
[0.73132306 0.79543483 0.72967815 0.7302106 ] 1
[0.7958336 0.7286084 0.728662  0.7286084] 0
[0.7958668 0.7286084 0.728662  0.7286084] 0
[0.7958999 0.7286084 0.7286084 0.7286084] 0
[0.73132306 0.7954681  0.72967815 0.7302106 ] 1
[0.73132306 0.79550135 0.72967815 0.7302106 ] 1
[0.73132306 0.7955346  0.72967815 0.7302106 ] 1
[0.73132306 0.7955679  0.72967815 0.7302106 ] 1
[0.73084724 0.730953   0.7311649  0.7941629 ] 3
[0.7959331 0.7286084 0.7286084 0.7286084] 0
[0.7959662 0.7286084 0.7286084 0.7286084] 0
[0.79599935 0.7286084  0.7286084  0.7286084 ] 0
[0.73084724 0.7309001  0

[0.7979704 0.728501  0.728501  0.7284474] 0
[0.7312174 0.7976442 0.7295182 0.7302637] 1
[0.7312174 0.7976768 0.7295182 0.7302637] 1
[0.7312174 0.7977095 0.7295182 0.7302637] 1
[0.73084724 0.7308471  0.7312178  0.7958999 ] 3
[0.7312174 0.7977421 0.7295182 0.7302637] 1
[0.73084724 0.7308471  0.7312178  0.7959331 ] 3
[0.73084724 0.7308471  0.7312178  0.7959662 ] 3
[0.7980029 0.728501  0.728501  0.7283936] 0
[0.73084724 0.7308471  0.7312178  0.79599935] 3
[0.79803544 0.728501   0.728501   0.7283936 ] 0
[0.73084724 0.7308471  0.7312178  0.7960325 ] 3
[0.73084724 0.7308471  0.7312178  0.79606557] 3
[0.79806805 0.728501   0.728501   0.7283936 ] 0
[0.73090017 0.7308471  0.7312178  0.79609865] 3
[0.7312174  0.79777473 0.7295182  0.7303169 ] 1
[0.73090017 0.7308471  0.7312178  0.7961318 ] 3
[0.73090017 0.7308471  0.7312178  0.7961649 ] 3
[0.73090017 0.7308471  0.7312178  0.79619795] 3
[0.7312174 0.79784   0.7295182 0.73037  ] 1
[0.79810053 0.728501   0.728501   0.7283936 ] 0
[0.7312174  0.797872

[0.7307943  0.7308471  0.73132336 0.79823065] 3
[0.800292   0.7283936  0.7284474  0.72828615] 0
[0.7312174  0.7995876  0.729358   0.73047614] 1
[0.7307943  0.7308471  0.73132336 0.79826313] 3
[0.7307943  0.7308471  0.73132336 0.7982956 ] 3
[0.7312174 0.7996197 0.729358  0.7305292] 1
[0.8003239  0.7283936  0.7284474  0.72828615] 0
[0.7307943  0.7308471  0.73132336 0.7983281 ] 3
[0.7312174 0.7996518 0.729358  0.7305292] 1
[0.7307943  0.7308471  0.73132336 0.7983606 ] 3
[0.7312174  0.79968387 0.729358   0.7305292 ] 1
[0.7312174 0.799716  0.729358  0.7305292] 1
Mean reward for each of the 3 bandits: [403.5  405.25 382.  ]
[0.80035585 0.7283936  0.7284474  0.72828615] 0
[0.7307943  0.7308471  0.73132336 0.79839295] 3
[0.7312174  0.79974806 0.729358   0.7305292 ] 1
[0.80038774 0.7283936  0.7284474  0.72828615] 0
[0.8004196  0.7283936  0.7284474  0.72828615] 0
[0.7307943  0.7308471  0.73132336 0.7984255 ] 3
[0.7307943  0.7308471  0.73132336 0.79845786] 3
[0.80045146 0.7283936  0.7284474  0.72

[0.73111176 0.80175096 0.729358   0.73047614] 1
[0.7307943 0.7308471 0.7313234 0.8004834] 3
[0.73111176 0.8017824  0.729358   0.73047614] 1
[0.73111176 0.80181396 0.729358   0.73047614] 1
[0.7307943  0.7308471  0.7313234  0.80051523] 3
[0.73111176 0.80184543 0.729358   0.73047614] 1
[0.73111176 0.80187696 0.729358   0.73047614] 1
[0.73111176 0.80190843 0.729358   0.73047614] 1
[0.8019399 0.7283936 0.7283399 0.728071 ] 0
[0.8019713 0.7283936 0.7283399 0.728071 ] 0
[0.7307943 0.7308471 0.7312706 0.8005471] 3
[0.7307943  0.7308471  0.7312706  0.80057895] 3
[0.7307943 0.7308471 0.7312706 0.8006107] 3
[0.73111176 0.8019399  0.729358   0.73047614] 1
[0.8020028 0.7283936 0.7283399 0.728071 ] 0
[0.8020342 0.7283936 0.7283399 0.728071 ] 0
[0.7307943 0.7308471 0.7312706 0.8006426] 3
[0.7307943 0.7308471 0.7312706 0.8006744] 3
[0.80206573 0.7283936  0.7283399  0.728071  ] 0
[0.73111176 0.8019713  0.729358   0.73047614] 1
[0.73111176 0.8020028  0.729358   0.73047614] 1
[0.7307943 0.7308471 0.73127

[0.8039356  0.7283399  0.7282324  0.72801715] 0
[0.7307413 0.7307412 0.7313234 0.8025048] 3
[0.73100597 0.8039974  0.7293046  0.7305292 ] 1
[0.7307413 0.7307412 0.7313234 0.8025361] 3
[0.73100597 0.8040283  0.7293046  0.7305292 ] 1
[0.7307413  0.7307412  0.7313234  0.80256736] 3
[0.73100597 0.8040591  0.7293046  0.7305292 ] 1
[0.73100597 0.80409    0.7293046  0.7305292 ] 1
[0.73100597 0.80412084 0.7293046  0.7305292 ] 1
[0.73100597 0.80415165 0.7293046  0.7305292 ] 1
[0.7307413 0.7307412 0.7313234 0.8025986] 3
[0.80396646 0.7283399  0.7282324  0.72796327] 0
[0.8039974  0.7283399  0.7282324  0.72796327] 0
[0.7306884 0.7308471 0.7313234 0.8026924] 3
[0.7309531 0.8042442 0.7293046 0.7305292] 1
[0.7306884 0.7308471 0.7313234 0.8027237] 3
[0.7306884 0.7308471 0.7313234 0.8027549] 3
[0.8040283  0.7283399  0.7282324  0.72796327] 0
[0.7309531  0.80427504 0.7293046  0.7305292 ] 1
[0.7309531 0.8043058 0.7293046 0.7305292] 1
[0.8040591  0.7283399  0.7282324  0.72796327] 0
[0.7309531  0.80433667 0

[0.8061995  0.7282324  0.72817856 0.72796327] 0
[0.80622977 0.7282324  0.72817856 0.72796327] 0
[0.7309531 0.8059266 0.7293046 0.7304762] 1
[0.7309531  0.80595696 0.7293046  0.7304762 ] 1
[0.80626    0.7282324  0.72817856 0.72796327] 0
[0.7308473  0.73095304 0.7312706  0.8045828 ] 3
[0.8062902  0.7282324  0.72817856 0.72796327] 0
[0.7308473  0.73095304 0.7312706  0.8046135 ] 3
[0.7308473  0.73095304 0.7312706  0.80464417] 3
[0.7309002  0.8059873  0.72925115 0.73052925] 1
[0.7308473  0.73095304 0.7312706  0.8046749 ] 3
[0.80632055 0.7282324  0.72817856 0.72796327] 0
[0.7308473  0.73095304 0.7312706  0.8047056 ] 3
[0.7308473  0.73095304 0.7312706  0.80473626] 3
[0.7308473  0.73095304 0.7312706  0.804767  ] 3
[0.7309002  0.8060176  0.72925115 0.73052925] 1
[0.7309002  0.806048   0.72925115 0.73052925] 1
[0.7308473  0.73095304 0.7312706  0.80479765] 3
[0.80635077 0.7282324  0.72817856 0.7279094 ] 0
[0.806381   0.7282324  0.72817856 0.7279094 ] 0
[0.7309002  0.80607826 0.72925115 0.73052925

[0.7308473  0.8074041  0.7291976  0.73058224] 1
[0.8085067  0.728071   0.72801715 0.7278555 ] 0
[0.7307413  0.73100597 0.7312706  0.8066829 ] 3
[0.8085364  0.728071   0.72801715 0.7278555 ] 0
[0.7307413  0.73100597 0.7312706  0.80671304] 3
[0.80856603 0.728071   0.72801715 0.7278555 ] 0
[0.8086252  0.728071   0.72801715 0.7278555 ] 0
[0.7307413  0.73100597 0.7312706  0.8067432 ] 3
[0.7308473  0.807434   0.7291976  0.73058224] 1
[0.7307413  0.73100597 0.7312706  0.8067733 ] 3
[0.7307413  0.73100597 0.7312706  0.8068034 ] 3
[0.80865484 0.728071   0.72801715 0.7278555 ] 0
[0.7307413  0.73100597 0.7312706  0.80683357] 3
[0.80868447 0.728071   0.72801715 0.7278555 ] 0
[0.80871403 0.728071   0.72801715 0.7278555 ] 0
[0.80874366 0.728071   0.72801715 0.7278555 ] 0
[0.7307413  0.73100597 0.7312706  0.80686367] 3
[0.7307413  0.73100597 0.7312706  0.80689377] 3
[0.7308473  0.8074939  0.7291976  0.73058224] 1
[0.8087732  0.728071   0.72801715 0.7278555 ] 0
[0.80880284 0.728071   0.72801715 0.7278

[0.8103587  0.7279094  0.72801715 0.72758573] 0
[0.7306884  0.73105884 0.7312706  0.80889153] 3
[0.7306884  0.73105884 0.7312706  0.80892104] 3
[0.7308473  0.8091276  0.7291976  0.73042315] 1
[0.8103879  0.7279094  0.72801715 0.72758573] 0
[0.7308473  0.8091571  0.7291976  0.73042315] 1
[0.81041706 0.7279094  0.72801715 0.72758573] 0
[0.81044614 0.7279094  0.72801715 0.72758573] 0
[0.7306884  0.73105884 0.7312706  0.8089506 ] 3
[0.7306884  0.73105884 0.7312706  0.80898005] 3
[0.8104753  0.7279094  0.72801715 0.72758573] 0
[0.7306884  0.73105884 0.7312706  0.8090096 ] 3
[0.7306884  0.73105884 0.7312706  0.8090391 ] 3
[0.7308473  0.8091866  0.7291976  0.73042315] 1
[0.7306884  0.73105884 0.7312706  0.8090686 ] 3
[0.7308473  0.80921596 0.7291976  0.73042315] 1
[0.8105043  0.7279094  0.72801715 0.72758573] 0
[0.81053346 0.7279094  0.72801715 0.72758573] 0
[0.7308473  0.80924547 0.7291976  0.73042315] 1
[0.7306884  0.73105884 0.7312706  0.8090981 ] 3
[0.7308473  0.8092749  0.7291976  0.7304

[0.7306884  0.7309531  0.7312178  0.81079507] 3
[0.81223667 0.7278016  0.72796327 0.7275318 ] 0
[0.7306884  0.7309531  0.7312178  0.81082404] 3
[0.8122653  0.7278016  0.72796327 0.7275318 ] 0
[0.7308473  0.81114274 0.72914416 0.73037004] 1
[0.7308473  0.8111717  0.72914416 0.73037004] 1
[0.7308473  0.8112006  0.72914416 0.73037004] 1
[0.7306884  0.7309531  0.7312178  0.81085306] 3
[0.8122939  0.7278016  0.72796327 0.7275318 ] 0
[0.7306884  0.7309531  0.7312178  0.81088215] 3
[0.81232256 0.7278016  0.72796327 0.7275318 ] 0
[0.7308473  0.8112295  0.72914416 0.73037004] 1
[0.8123511  0.7278016  0.72796327 0.7275318 ] 0
[0.8123797  0.7278016  0.72796327 0.7275318 ] 0
[0.8124083  0.7278016  0.72796327 0.7275318 ] 0
[0.7308473  0.81125844 0.72914416 0.73037004] 1
[0.81243694 0.7277476  0.72796327 0.7275318 ] 0
[0.8124655  0.7277476  0.72796327 0.7275318 ] 0
[0.81249404 0.7277476  0.72796327 0.7275318 ] 0
[0.81252265 0.7277476  0.72796327 0.7275318 ] 0
[0.7306884  0.7309531  0.7312178  0.8109

[0.73063534 0.7309531  0.731165   0.81249404] 3
[0.73063534 0.7309531  0.731165   0.81252265] 3
[0.73063534 0.7309531  0.731165   0.8125512 ] 3
[0.8143629  0.72763973 0.7278555  0.72736967] 0
[0.81439096 0.72763973 0.7278555  0.72736967] 0
[0.73063534 0.7309531  0.731165   0.8125797 ] 3
[0.7309002  0.81297857 0.72903717 0.73015755] 1
[0.81441903 0.72763973 0.7278555  0.72736967] 0
[0.73063534 0.7309531  0.731165   0.81260824] 3
[0.73084736 0.813007   0.72903717 0.73015755] 1
[0.73063534 0.7309531  0.731165   0.8126368 ] 3
[0.73084736 0.8130355  0.72903717 0.73015755] 1
[0.8144471  0.72763973 0.7278555  0.72736967] 0
[0.73063534 0.7309531  0.731165   0.81266534] 3
[0.73063534 0.7309531  0.731165   0.81269383] 3
[0.73063534 0.7309531  0.731165   0.8127223 ] 3
Mean reward for each of the 3 bandits: [520.5  510.25 489.5 ]
[0.73063534 0.7309531  0.731165   0.8127509 ] 3
[0.8144751  0.72763973 0.7278555  0.72736967] 0
[0.8145032  0.72763973 0.7278555  0.72736967] 0
[0.81453115 0.72763973 0.7

[0.73058236 0.73090017 0.7313235  0.8143629 ] 3
[0.73079437 0.81464314 0.7289301  0.7300512 ] 1
[0.73058236 0.73090017 0.7313235  0.81439096] 3
[0.73058236 0.73090017 0.7313235  0.81441903] 3
[0.73079437 0.81467116 0.7289301  0.7300512 ] 1
[0.81633675 0.7275318  0.7276937  0.7272615 ] 0
[0.73058236 0.73090017 0.7313235  0.8144471 ] 3
[0.73079437 0.8146992  0.7289301  0.7300512 ] 1
[0.73058236 0.73090017 0.7313235  0.8144751 ] 3
[0.73058236 0.73090017 0.7313235  0.8145032 ] 3
[0.81636435 0.7274778  0.7276937  0.7272615 ] 0
[0.73079437 0.8147271  0.7289301  0.7300512 ] 1
[0.73058236 0.73090017 0.7313235  0.81453115] 3
[0.73079437 0.81475514 0.7289301  0.7300512 ] 1
[0.8163919 0.7274778 0.7276937 0.7272615] 0
[0.73079437 0.81478304 0.7289301  0.7300512 ] 1
[0.81641936 0.7274778  0.7276937  0.7272615 ] 0
[0.8164744 0.7274778 0.7276937 0.7272615] 0
[0.73058236 0.73090017 0.7313235  0.81455916] 3
[0.81650186 0.7274778  0.7276937  0.7272615 ] 0
[0.8165294 0.7274778 0.7276937 0.7272615] 0
[0.7

[0.81803024 0.72736967 0.7276937  0.7272074 ] 0
[0.7306884  0.73090017 0.7313763  0.81617147] 3
[0.7306884  0.73090017 0.7313763  0.816199  ] 3
[0.7306884  0.73090017 0.7313763  0.8162266 ] 3
[0.7306884  0.73090017 0.7313235  0.81625414] 3
[0.73084736 0.8166393  0.72887653 0.7300512 ] 1
[0.8180573  0.72736967 0.7276937  0.7272074 ] 0
[0.8180844  0.72736967 0.7276937  0.7272074 ] 0
[0.73084736 0.8166667  0.72887653 0.7300512 ] 1
[0.7306884  0.73090017 0.7313235  0.81628174] 3
[0.8181114  0.72736967 0.7276937  0.7272074 ] 0
[0.7306884  0.73090017 0.7313235  0.8163093 ] 3
[0.7306884  0.73090017 0.7313235  0.81633675] 3
[0.8181385  0.72736967 0.7276937  0.7272074 ] 0
[0.8181656  0.72736967 0.7276937  0.7272074 ] 0
[0.73084736 0.81669414 0.72887653 0.7300512 ] 1
[0.73084736 0.8167216  0.72887653 0.7300512 ] 1
[0.8181926  0.72736967 0.7276937  0.7272074 ] 0
[0.81821966 0.72736967 0.7276937  0.7272074 ] 0
[0.7306884  0.73090017 0.7313235  0.81636435] 3
[0.73084736 0.8167491  0.72887653 0.7300

[0.73084736 0.81821966 0.7287157  0.729998  ] 1
[0.7306354 0.7309531 0.7312707 0.8181926] 3
[0.73084736 0.8182467  0.7287157  0.729998  ] 1
[0.8198293  0.7272074  0.72758573 0.7271533 ] 0
[0.81985587 0.7272074  0.72758573 0.7271533 ] 0
[0.73084736 0.8182738  0.7287157  0.729998  ] 1
[0.7306354  0.7309531  0.7312707  0.81821966] 3
[0.73084736 0.8183007  0.7287157  0.729998  ] 1
[0.7306354 0.7309531 0.7312707 0.8182467] 3
[0.8198825  0.7272074  0.72758573 0.7271533 ] 0
[0.7306354 0.7309531 0.7312707 0.8182738] 3
[0.7306354 0.7309531 0.7312707 0.8183007] 3
[0.7306354 0.7309531 0.7312707 0.8183278] 3
[0.8199091  0.7272074  0.72758573 0.7271533 ] 0
[0.8199357  0.7272074  0.72758573 0.7271533 ] 0
[0.73084736 0.8183548  0.7286621  0.729998  ] 1
[0.7306354 0.7309531 0.7312707 0.8183548] 3
[0.8199622  0.7272074  0.72758573 0.7271533 ] 0
[0.81998885 0.7272074  0.72758573 0.7271533 ] 0
[0.8200154  0.7272074  0.72758573 0.7271533 ] 0
[0.73084736 0.8183818  0.7286621  0.729998  ] 1
[0.820042   0.72

[0.7307944  0.8198825  0.7286621  0.72994477] 1
[0.73052937 0.73090017 0.7313235  0.8201481 ] 3
[0.73084736 0.8199091  0.7286621  0.72994477] 1
[0.8215445 0.7269909 0.7274237 0.7271533] 0
[0.73084736 0.8199357  0.7286621  0.72994477] 1
[0.73084736 0.8199622  0.7286621  0.72994477] 1
[0.73084736 0.81998885 0.7286621  0.72994477] 1
[0.73084736 0.8200154  0.7286621  0.72994477] 1
[0.73090035 0.820042   0.7286621  0.72994477] 1
[0.73052937 0.73090017 0.7313235  0.8201747 ] 3
[0.8215707 0.7269909 0.7274237 0.7271533] 0
[0.73052937 0.73090017 0.7313235  0.82020116] 3
[0.73052937 0.73090017 0.7313235  0.8202277 ] 3
[0.73052937 0.73090017 0.7313235  0.82025415] 3
[0.82159686 0.7269909  0.7274237  0.7271533 ] 0
[0.82162297 0.7269909  0.7274237  0.7271533 ] 0
[0.73052937 0.73090017 0.7313235  0.82028073] 3
[0.82164913 0.7269909  0.7274237  0.7271533 ] 0
[0.8216753 0.7269909 0.7274237 0.7271533] 0
[0.73052937 0.73090017 0.7313235  0.8203072 ] 3
[0.82170135 0.7269909  0.7274237  0.7271533 ] 0
[0.7

[0.823308   0.7268282  0.72736967 0.7269909 ] 0
[0.7307944  0.8217798  0.7286085  0.72994477] 1
[0.7307944  0.82180583 0.7286085  0.72994477] 1
[0.73052937 0.7309531  0.7313235  0.8217798 ] 3
[0.82333374 0.7268282  0.72736967 0.7269909 ] 0
[0.73052937 0.7309531  0.7313235  0.82180583] 3
[0.7307944  0.82183194 0.7286085  0.72994477] 1
[0.82335943 0.7268282  0.72736967 0.7269909 ] 0
[0.8233851  0.7268282  0.72736967 0.7269909 ] 0
[0.7307944  0.82185805 0.7286085  0.72994477] 1
[0.73052937 0.7309531  0.7313235  0.82183194] 3
[0.73052937 0.7309531  0.7313235  0.82185805] 3
[0.8234108  0.7268282  0.72736967 0.7269909 ] 0
[0.7307944  0.82188416 0.7286085  0.72994477] 1
[0.8234365  0.7268282  0.72736967 0.7269909 ] 0
[0.7307944  0.82191014 0.7286085  0.72994477] 1
[0.8234621  0.7268282  0.72736967 0.7269909 ] 0
[0.73052937 0.7309531  0.7313235  0.82188416] 3
[0.8234878  0.7268282  0.72736967 0.7269909 ] 0
[0.7307944  0.8219623  0.7286085  0.72994477] 1
[0.7307944  0.82198834 0.7286085  0.7299

[0.82499015 0.7267197  0.72736967 0.72688246] 0
[0.8250155  0.7267197  0.72736967 0.72688246] 0
[0.73058236 0.731006   0.7311651  0.82351345] 3
[0.8250407  0.7267197  0.72736967 0.72688246] 0
[0.82506603 0.7267197  0.72736967 0.72688246] 0
[0.73068845 0.8235647  0.72855484 0.7299448 ] 1
[0.73068845 0.82359046 0.72855484 0.7299448 ] 1
[0.73068845 0.8236161  0.72855484 0.7299448 ] 1
[0.8250912  0.7267197  0.72736967 0.72688246] 0
[0.73058236 0.731006   0.7311651  0.8235391 ] 3
[0.73058236 0.731006   0.7311651  0.8235647 ] 3
[0.73068845 0.8236417  0.72855484 0.7299448 ] 1
[0.8251164  0.7267197  0.72736967 0.72688246] 0
[0.73068845 0.8236673  0.72855484 0.7299448 ] 1
[0.73068845 0.8236929  0.72855484 0.7299448 ] 1
[0.82514167 0.7267197  0.72736967 0.72688246] 0
[0.8251669  0.7267197  0.72736967 0.72688246] 0
[0.73068845 0.8237185  0.72855484 0.7299448 ] 1
[0.73058236 0.7309531  0.7311651  0.82359046] 3
[0.73068845 0.8237441  0.72850114 0.7299448 ] 1
[0.73058236 0.7309531  0.7311651  0.8236

[0.82659423 0.7267197  0.7272074  0.72655684] 0
[0.8266191  0.7267197  0.7272074  0.72655684] 0
[0.8266439  0.7267197  0.7272074  0.72655684] 0
[0.82666874 0.7267197  0.7272074  0.72655684] 0
[0.73063546 0.82519215 0.7283937  0.7299448 ] 1
[0.73063546 0.8252173  0.7283937  0.7299448 ] 1
[0.73063546 0.8252426  0.7283937  0.7299448 ] 1
[0.8266936  0.7267197  0.7272074  0.72655684] 0
[0.7305825  0.82526773 0.7283937  0.7299448 ] 1
[0.7305825 0.825293  0.7283937 0.7299448] 1
[0.8267184  0.7267197  0.7272074  0.72655684] 0
[0.7305825  0.82531816 0.7283937  0.7299448 ] 1
[0.7305824  0.731006   0.73111224 0.82519215] 3
[0.82674325 0.7267197  0.7272074  0.72655684] 0
[0.7305825 0.8253433 0.7283937 0.7299448] 1
[0.826768   0.7267197  0.7272074  0.72655684] 0
[0.7305824  0.73095316 0.73111224 0.8252173 ] 3
[0.7305825 0.8253685 0.7283937 0.7299448] 1
[0.7305824  0.73095316 0.73111224 0.8252426 ] 3
[0.7305825 0.8253937 0.7283937 0.7299448] 1
[0.7305824  0.73095316 0.73111224 0.82526773] 3
[0.82679

[0.8283431 0.7266654 0.7271533 0.7264481] 0
[0.7305825  0.8270901  0.72833997 0.7299448 ] 1
[0.7305824  0.73095316 0.7310594  0.8266191 ] 3
[0.7305824  0.73095316 0.7310594  0.8266439 ] 3
[0.82836753 0.7266654  0.7271533  0.7264481 ] 0
[0.7305824  0.73095316 0.7310594  0.82666874] 3
[0.8283919  0.7266654  0.7271533  0.72639376] 0
[0.7305825  0.82711476 0.7282862  0.7299448 ] 1
[0.7306354  0.73095316 0.7310594  0.8266936 ] 3
[0.7305825 0.8271395 0.7282862 0.7299448] 1
[0.8284163  0.7266654  0.7271533  0.72639376] 0
[0.7306354  0.73095316 0.7310594  0.8267184 ] 3
[0.7305825 0.8271642 0.7282862 0.7299448] 1
[0.7306354  0.73095316 0.7310594  0.82674325] 3
[0.82844067 0.7266654  0.7271533  0.72639376] 0
[0.82846504 0.7266654  0.7271533  0.72639376] 0
[0.8284894  0.7266654  0.7271533  0.72639376] 0
[0.7306354  0.73095316 0.7310594  0.826768  ] 3
[0.7306354  0.73095316 0.7310594  0.82679284] 3
[0.7306354  0.73095316 0.7310594  0.82681763] 3
[0.7306354  0.73095316 0.7310594  0.8268425 ] 3
[0.7

[0.7304764  0.82844067 0.72828627 0.73005134] 1
[0.82972443 0.72655684 0.7270991  0.72623056] 0
[0.73042333 0.8284894  0.72828627 0.73005134] 1
[0.7306354  0.73095316 0.7310594  0.8283431 ] 3
[0.8297485  0.72655684 0.7270991  0.72623056] 0
[0.7306354  0.73095316 0.7310594  0.82836753] 3
[0.7306354  0.73095316 0.7310594  0.8283919 ] 3
[0.73042333 0.8285138  0.72828627 0.73005134] 1
[0.7306354  0.73095316 0.7310594  0.8284163 ] 3
[0.82977253 0.72655684 0.7270991  0.72623056] 0
[0.7306354  0.73095316 0.7310594  0.82844067] 3
[0.7306354  0.73095316 0.7310594  0.82846504] 3
[0.73042333 0.8285382  0.72828627 0.73005134] 1
[0.7306354  0.73095316 0.7310594  0.8284894 ] 3
[0.8297966  0.72655684 0.7270991  0.72623056] 0
[0.73042333 0.8285626  0.72828627 0.73005134] 1
[0.73042333 0.8285869  0.72828627 0.73005134] 1
[0.73042333 0.8286112  0.72828627 0.73005134] 1
[0.7306354  0.73095316 0.7310594  0.8285138 ] 3
[0.73042333 0.8286356  0.72828627 0.73005134] 1
[0.73042333 0.8286599  0.72828627 0.7300

[0.73047644 0.8301565  0.7281787  0.7299981 ] 1
[0.73063546 0.73084736 0.7310065  0.8298687 ] 3
[0.83125186 0.72639376 0.727045   0.72617614] 0
[0.73042333 0.8301804  0.7281787  0.7299981 ] 1
[0.73063546 0.73084736 0.7310594  0.82989264] 3
[0.73063546 0.73084736 0.7310594  0.8299167 ] 3
[0.8312755  0.72639376 0.727045   0.72617614] 0
[0.73063546 0.73084736 0.7310594  0.8299407 ] 3
[0.8312991  0.72639376 0.727045   0.72617614] 0
[0.7303703 0.8302044 0.7281787 0.7299981] 1
[0.8313228  0.72639376 0.727045   0.72617614] 0
[0.7303703 0.8302283 0.7281787 0.7299981] 1
[0.7303703  0.83025223 0.7281787  0.7299981 ] 1
[0.7303703  0.83027613 0.7281787  0.7299981 ] 1
[0.7303703 0.8303001 0.7281787 0.7299981] 1
[0.83134645 0.72639376 0.727045   0.72617614] 0
[0.7303703 0.830324  0.7281787 0.7299981] 1
[0.83137006 0.7263394  0.727045   0.72617614] 0
[0.7303703 0.8303479 0.7281787 0.7299981] 1
[0.73063546 0.73084736 0.7310065  0.82996476] 3
[0.8313937  0.7263394  0.727045   0.72617614] 0
[0.7303703 0

[0.73063546 0.7307414  0.7308478  0.8314174 ] 3
[0.73063546 0.7307414  0.7308478  0.83144104] 3
[0.83277804 0.72628504 0.727045   0.72606725] 0
[0.73063546 0.7307414  0.7308478  0.8314646 ] 3
[0.8328013  0.72628504 0.727045   0.72606725] 0
[0.7303171  0.8318418  0.72807103 0.7299448 ] 1
[0.73063546 0.7307414  0.7308478  0.83148825] 3
[0.8328246  0.72628504 0.727045   0.72606725] 0
[0.73063546 0.7307414  0.7308478  0.8315119 ] 3
[0.7303171  0.8318653  0.72807103 0.7299448 ] 1
[0.7303171  0.8318888  0.72807103 0.7299448 ] 1
[0.73063546 0.7307414  0.7308478  0.83153546] 3
[0.83284783 0.72628504 0.7269909  0.72606725] 0
[0.7303171  0.83191234 0.72807103 0.7299448 ] 1
[0.73063546 0.7307414  0.7308478  0.83155906] 3
[0.73063546 0.7307414  0.7308478  0.8315826 ] 3
[0.7303171  0.8319358  0.72807103 0.7299448 ] 1
[0.7306885 0.7307414 0.7308478 0.8316062] 3
[0.83287114 0.72628504 0.7269909  0.72606725] 0
[0.8328944  0.72628504 0.7269909  0.72606725] 0
[0.8329176  0.72628504 0.7269909  0.72606725

[0.8343024  0.72623056 0.72688246 0.7260127 ] 0
[0.8343253  0.72623056 0.72688246 0.7260127 ] 0
[0.7303171  0.83340466 0.7280172  0.7298384 ] 1
[0.7303171  0.83342785 0.7280172  0.7298384 ] 1
[0.7305825 0.7307414 0.7308478 0.8331499] 3
[0.7305825  0.7307414  0.7308478  0.83317304] 3
[0.8343482  0.72623056 0.72688246 0.7260127 ] 0
[0.7305825 0.7307414 0.7308478 0.8331962] 3
[0.83437115 0.72623056 0.72688246 0.7260127 ] 0
[0.83439404 0.72623056 0.72688246 0.7260127 ] 0
[0.7303171 0.833451  0.7280172 0.7298384] 1
[0.7303171  0.83347404 0.7280172  0.7298384 ] 1
[0.7303171  0.83349717 0.7280172  0.7298384 ] 1
[0.7305825 0.7307414 0.7308478 0.8332194] 3
[0.7303171 0.8335203 0.7280172 0.7298384] 1
[0.7303171  0.83354336 0.7280172  0.7298384 ] 1
[0.7305825 0.7307414 0.7308478 0.8332426] 3
[0.7303171 0.8335665 0.7280172 0.7298384] 1
[0.7303171 0.8335895 0.7280172 0.7298384] 1
[0.7305825 0.7307414 0.7308478 0.8332658] 3
[0.7305825 0.7307414 0.7308478 0.8332889] 3
[0.8344169  0.72623056 0.7268824

[0.7303172 0.8348734 0.7279633 0.7298384] 1
[0.7305295  0.73068845 0.7308478  0.8345769 ] 3
[0.8360945  0.72590375 0.72688246 0.7260127 ] 0
[0.83611697 0.72590375 0.72688246 0.7260127 ] 0
[0.8361395  0.72590375 0.72688246 0.7260127 ] 0
[0.7305295  0.73068845 0.7308478  0.83459973] 3
[0.7303172  0.83489615 0.7279633  0.7298384 ] 1
[0.7303172 0.8349189 0.7279633 0.7298384] 1
[0.8361619  0.72590375 0.72688246 0.7260127 ] 0
[0.7303172 0.8349417 0.7279633 0.7298384] 1
[0.7303172  0.83496433 0.7279633  0.7298384 ] 1
[0.7303172 0.8349871 0.7279633 0.7298384] 1
[0.8361843  0.72590375 0.72688246 0.7260127 ] 0
[0.83620673 0.72590375 0.72688246 0.7260127 ] 0
[0.7305295  0.7307414  0.7307948  0.83462256] 3
[0.7305295  0.7307414  0.7307948  0.83464545] 3
[0.7303172 0.8350099 0.7279633 0.7298384] 1
[0.8362292  0.72590375 0.72688246 0.7260127 ] 0
[0.8362517  0.72590375 0.72688246 0.7260127 ] 0
[0.83627415 0.72590375 0.72688246 0.7260127 ] 0
[0.7303172 0.8350326 0.7279633 0.7298384] 1
[0.7303172 0.835