NN on dcdc non bdd 

Fully connected


In [1]:
# These are all the modules we'll be using later. Make sure you can import them
# before proceeding further.
from __future__ import print_function
import numpy as np
import tensorflow as tf
from six.moves import cPickle as pickle
from six.moves import range

import matplotlib.pyplot as plt
# plot param
%matplotlib inline
plt.rcParams['figure.figsize'] = (22.0, 12.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'
plt.style.use('ggplot')

First, manipulate the input and output data

Reformat into a shape that's more adapted to the models we're going to train:
- data as a flat matrix,
- labels as float 1-hot encodings.

In [2]:
# parse the controller file
f = open('controller.scs', "r")

In [3]:
lines = []

Skip the header part and go straight to the state-action pair

In [4]:
for line in f:
    if '#MATRIX:DATA\n' in line:                
        for line in f: # now you are at the lines you want
            # skip the #BEGIN 
            # read the state-actions
            lines = f.readlines()

In [5]:
# take the state as the train dataset
ltrain_dataset = []
for x in lines:
    ltrain_dataset.append(x.split(' ')[0])
del ltrain_dataset[-1] # delete the string #END at the end of the file 

In [6]:
# convert to the numpy array with float32 data type
train_dataset = np.asarray(ltrain_dataset)
train_dataset = train_dataset.astype(np.float32)
train_dataset.shape

(593089,)

In [7]:
# take the action(s) [column 1:-1] / the rest of the integer except the state
ltrain_label = []
for x in lines:
    ltrain_label.append(x.split(' ')[1:-1])
del ltrain_label[-1] # delete the string #END at the end of the file  

In [8]:
# convert to numpy array, note that the result is still not in one hot encoding format
train_label = np.asarray(ltrain_label)
train_label

array([list(['1']), list(['1']), list(['1']), ..., list(['0']),
       list(['0']), list(['0'])], dtype=object)

Iterate from here

In [9]:
# define number of samples
num_samples = train_dataset.shape[0]
num_samples

593089

In [10]:
# create now array to be filled by the encoded label
train_label_hot = np.zeros([num_samples,2], dtype=np.float32)
train_label_hot.shape

(593089, 2)

In [11]:
ltrain_label[0]

['1']

In [12]:
# encode label to one hot encoding format
for i in range(num_samples):
    if train_label[i] == ['0']:
        train_label_hot[i] = [1, 0]
    elif train_label[i] == ['1']:
        train_label_hot[i] = [0, 1]
    elif train_label[i] == ['0','1']:
        train_label_hot[i] = [1, 1]

Small dataset

In [21]:
# define the new number of samples for debugging purpose
num_samples = 40
# define batch offset to limit the desired dataset index
batch_off = 20000+16800-87-25
# slice the train label to the desired index
train_label_hot = train_label_hot[batch_off:batch_off + num_samples]
train_label_hot.shape

(40, 2)

In [22]:
# do the same thing to the dataset and add dimension on the column
train_dataset_reform = train_dataset[batch_off:batch_off + num_samples, None]
train_dataset_reform.shape

(40, 1)

Execute this to get the full batch

In [13]:
train_dataset_reform = train_dataset[:, None]
train_dataset_reform.shape

(593089, 1)

# NN

In [14]:
def accuracy(predictions, labels):
  return (100.0 * np.sum(np.argmax(predictions, 1) == np.argmax(labels, 1))
          / predictions.shape[0])


In [67]:
def accuracy(predictions, labels):
  return (100.0 * np.sum(predictions == labels) / predictions.shape[1] / predictions.shape[0])

In [15]:
train_dataset_reform[0]

array([459.], dtype=float32)

In [16]:
train_dataset_reform[-1]

array([638857.], dtype=float32)

In [17]:
train_label_hot[0]

array([0., 1.], dtype=float32)

In [18]:
train_label_hot[-1]

array([1., 0.], dtype=float32)

In [19]:
num_samples

593089

In [20]:
num_label = 2

In [70]:
batch_size = int(num_samples/100)
hidden_size = 1024
hidden_size2 = 512
hidden_size3 = 256
hidden_size4 = 128

# 20, 100, 500, 1000, 2000

# graph = tf.Graph()
# with tf.device('/device:GPU:0'):
# with graph.as_default():
# Input data. For the training data, we use a placeholder that will be fed
# at run time with a training minibatch.
tf_train_dataset = tf.placeholder(tf.float32, shape=(batch_size, 1))
tf_train_labels = tf.placeholder(tf.float32, shape=(batch_size, num_label))
# tf_valid_dataset = tf.constant(valid_dataset)
tf_test_dataset = tf.placeholder(tf.float32, shape=(batch_size, num_label))
tf_test_labels = tf.placeholder(tf.float32, shape=(batch_size, num_label))

# Variables.
weights1 = tf.Variable(tf.truncated_normal([1, hidden_size]))
biases1 = tf.Variable(tf.zeros([hidden_size]))

# weights2 = tf.Variable(tf.truncated_normal([hidden_size, num_label]))
# biases2 = tf.Variable(tf.zeros([num_label]))

weights2 = tf.Variable(tf.truncated_normal([hidden_size, hidden_size2]))
biases2 = tf.Variable(tf.zeros([hidden_size2]))

weights3 = tf.Variable(tf.truncated_normal([hidden_size2, hidden_size3]))
biases3 = tf.Variable(tf.zeros([hidden_size3]))

# weights4 = tf.Variable(tf.truncated_normal([hidden_size3, num_label]))
# biases4 = tf.Variable(tf.zeros([num_label]))
weights4 = tf.Variable(tf.truncated_normal([hidden_size3, hidden_size4]))
biases4 = tf.Variable(tf.zeros([hidden_size4]))

weights5 = tf.Variable(tf.truncated_normal([hidden_size4, num_label]))
biases5 = tf.Variable(tf.zeros([num_label]))

# Training computation.
logits1 = tf.matmul(tf_train_dataset, weights1) + biases1  
relu_act_func = tf.nn.relu(logits1)
logits2 = tf.matmul(relu_act_func, weights2) + biases2

relu_act_func2 = tf.nn.relu(logits2)
logits3 = tf.matmul(relu_act_func2, weights3) + biases3

relu_act_func3 = tf.nn.relu(logits3)
logits4 = tf.matmul(relu_act_func3, weights4) + biases4

relu_act_func4 = tf.nn.relu(logits4)
logits5 = tf.matmul(relu_act_func4, weights5) + biases5

logits = logits5

# loss calculation
# loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=tf_train_labels, logits=logits5))
loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(labels=tf_train_labels, logits=logits5))

# Predictions for the training, validation, and test data.
# train_prediction = tf.nn.softmax(logits5)
train_prediction = tf.round(tf.sigmoid(logits5))

# loss = tf.reduce_mean(tf.losses.absolute_difference(labels=tf_train_labels, predictions=train_prediction))

loss_summary = tf.summary.scalar('loss', loss)

# Optimizer.
# optimizer = tf.train.GradientDescentOptimizer(0.0001).minimize(loss)
optimizer = tf.train.AdamOptimizer(2).minimize(loss)

# Predictions for the training, validation, and test data.
# train_prediction = tf.nn.softmax(logits4)

#valid_prediction = tf.nn.softmax(
#    tf.matmul(tf.nn.relu(tf.matmul(tf_valid_dataset, weights1) + biases1), weights2) + biases2)
# test_prediction = tf.nn.softmax(tf.matmul(tf.nn.relu(tf.matmul(tf.nn.relu(tf.matmul(tf.nn.relu(
  #  tf.matmul(tf_test_dataset, weights1) + biases1), weights2) + biases2), weights3) + biases3), weights4)+biases4)
 
# test_prediction = tf.sigmoid(tf.matmul(tf.nn.relu(tf.matmul(tf.nn.relu(tf.matmul(tf.nn.relu(tf.matmul(tf.nn.relu(tf.matmul(
#        tf_test_dataset, weights1) + biases1), weights2) + biases2), weights3) + biases3), weights4)+biases4),weights5) + biases5)
     
    # writer = tf.summary.FileWriter('./vehicle', tf.get_default_graph())


In [71]:
batch_size

5930

In [72]:
num_samples

593089

In [73]:
iteration_one_epoch = np.floor(num_samples / batch_size)
iteration_one_epoch

100.0

In [74]:
train_label_hot.shape

(593089, 2)

In [75]:
train_dataset_reform.shape

(593089, 1)

In [76]:
num_steps = int(iteration_one_epoch*10)
loss_history = []

with tf.Session() as session:
# with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as session:
#with tf.Session(graph=graph) as session:
    tf.global_variables_initializer().run()
    print("Initialized")
    for step in range(num_steps):
        # Pick an offset within the training data, which has been randomized.
        # Note: we could use better randomization across epochs.
        offset = (step * batch_size) % (train_label_hot.shape[0] - batch_size)
        # Generate a minibatch.
        batch_data = train_dataset_reform[offset:(offset + batch_size), :]
        batch_labels = train_label_hot[offset:(offset + batch_size), :]

        # print(offset)
        # Prepare a dictionary telling the session where to feed the minibatch.
        # The key of the dictionary is the placeholder node of the graph to be fed,
        # and the value is the numpy array to feed to it.
        feed_dict = {tf_train_dataset : batch_data, tf_train_labels : batch_labels}
        _, l, predictions, added_summary, logits_check = session.run(
            [optimizer, loss, train_prediction, loss_summary, logits], feed_dict=feed_dict)

        # writer.add_summary(added_summary)
        loss_history.append(l)
        # print(offset, batch_size)
        print("Minibatch loss at step %d: %f" % (step, l))
        print("Minibatch accuracy: %.1f%%" % accuracy(predictions, batch_labels))
        print(batch_labels)
        print(predictions)
        # if (step % iteration_one_epoch == 0):
        # print("Minibatch loss at step %d: %f" % (step, l))
            # print("Minibatch accuracy: %.1f%%" % accuracy(predictions, batch_labels))
            # print(logits_check)
            # print(weights1.eval())
            # print("Validation accuracy: %.1f%%" % accuracy(valid_prediction.eval(), valid_labels))
    
    # Do for the test batch
    acc = 0
    for step in range(int(iteration_one_epoch)):
        # Pick an offset within the training data, which has been randomized.
        # Note: we could use better randomization across epochs.
        offset = (step * batch_size) % (train_label_hot.shape[0] - batch_size)
        # Generate a minibatch.
        batch_data = train_dataset_reform[offset:(offset + batch_size), :]
        batch_labels = train_label_hot[offset:(offset + batch_size), :]

        # print(offset)
        # Prepare a dictionary telling the session where to feed the minibatch.
        # The key of the dictionary is the placeholder node of the graph to be fed,
        # and the value is the numpy array to feed to it.
        feed_dict = {tf_train_dataset : batch_data, tf_train_labels : batch_labels}
        test_predictions = session.run(train_prediction, feed_dict=feed_dict)
        print(offset, offset + batch_size)
        print(batch_labels)
        print(test_predictions)
        batch_acc = accuracy(test_predictions, batch_labels)
        print("Minibatch accuracy: %.1f%%" % batch_acc)
        acc = acc + batch_acc

    print(acc)

Initialized
Minibatch loss at step 0: 4785019.500000
Minibatch accuracy: 50.0%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Minibatch loss at step 1: 0.000000
Minibatch accuracy: 100.0%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 2: 0.000000
Minibatch accuracy: 100.0%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 3: 0.000000
Minibatch accuracy: 100.0%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 4: 0.000000
Minibatch accuracy: 100.0%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 5: 0.000000
Minibatch accuracy: 100.0%
[[0. 1.]
 [

Minibatch loss at step 44: 168742.468750
Minibatch accuracy: 64.3%
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 45: 296354.187500
Minibatch accuracy: 23.7%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Minibatch loss at step 46: 103039.625000
Minibatch accuracy: 76.7%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 47: 125228.109375
Minibatch accuracy: 77.3%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 48: 128355.445312
Minibatch accuracy: 75.6%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 49: 63890.683594
Minibatch accuracy: 78.0%

Minibatch loss at step 88: 13402.914062
Minibatch accuracy: 74.8%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 89: 74448.257812
Minibatch accuracy: 22.6%
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Minibatch loss at step 90: 28730.724609
Minibatch accuracy: 24.7%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Minibatch loss at step 91: 29361.978516
Minibatch accuracy: 78.1%
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 92: 53222.906250
Minibatch accuracy: 78.4%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 93: 52571.531250
Minibatch accuracy: 80.3%
[[1.

Minibatch loss at step 132: 62460.261719
Minibatch accuracy: 77.6%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 133: 146253.968750
Minibatch accuracy: 66.2%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 134: 81646.609375
Minibatch accuracy: 64.7%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 135: 132275.281250
Minibatch accuracy: 75.8%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 136: 208817.515625
Minibatch accuracy: 35.6%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
Minibatch loss at step 137: 195759.250000
Minibatch accuracy: 

Minibatch loss at step 176: 29064.439453
Minibatch accuracy: 64.6%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 177: 24812.009766
Minibatch accuracy: 64.5%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 178: 12237.407227
Minibatch accuracy: 74.8%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 179: 48715.515625
Minibatch accuracy: 36.0%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
Minibatch loss at step 180: 15339.660156
Minibatch accuracy: 75.3%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 181: 17798.101562
Minibatch accuracy: 63.7

Minibatch loss at step 220: 82218.265625
Minibatch accuracy: 67.2%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 221: 69448.757812
Minibatch accuracy: 64.7%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 222: 26217.726562
Minibatch accuracy: 66.1%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 223: 56456.851562
Minibatch accuracy: 76.5%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 224: 74521.226562
Minibatch accuracy: 78.2%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 225: 93666.429688
Minibatch accuracy: 75.5

Minibatch loss at step 264: 17303.562500
Minibatch accuracy: 77.7%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 265: 3554.596191
Minibatch accuracy: 75.6%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 266: 34618.960938
Minibatch accuracy: 64.1%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 267: 43763.261719
Minibatch accuracy: 65.3%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 268: 36792.171875
Minibatch accuracy: 65.1%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 269: 15701.739258
Minibatch accuracy: 64.2%

Minibatch loss at step 308: 21226.017578
Minibatch accuracy: 76.6%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 309: 14828.098633
Minibatch accuracy: 78.5%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 310: 6106.424316
Minibatch accuracy: 67.2%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 311: 6684.471680
Minibatch accuracy: 64.8%
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 312: 12834.630859
Minibatch accuracy: 76.7%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 313: 14287.954102
Minibatch accuracy: 77.3%


Minibatch loss at step 352: 26762.339844
Minibatch accuracy: 65.4%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 353: 22961.738281
Minibatch accuracy: 65.5%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 354: 8901.530273
Minibatch accuracy: 64.4%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 355: 13753.146484
Minibatch accuracy: 75.1%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 356: 21292.144531
Minibatch accuracy: 77.5%
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 357: 26297.324219
Minibatch accuracy: 76.2%

Minibatch loss at step 396: 7663.406250
Minibatch accuracy: 70.0%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 397: 17545.837891
Minibatch accuracy: 50.0%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 398: 4929.116211
Minibatch accuracy: 50.0%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Minibatch loss at step 399: 0.000000
Minibatch accuracy: 100.0%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 400: 0.000000
Minibatch accuracy: 100.0%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 401: 0.000000
Minibatch accuracy: 100.0%
[[0. 1.]


Minibatch loss at step 440: 5125.434570
Minibatch accuracy: 75.4%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 441: 4734.665527
Minibatch accuracy: 77.6%
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 442: 1174.235718
Minibatch accuracy: 76.4%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 443: 10038.525391
Minibatch accuracy: 65.0%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 444: 12280.011719
Minibatch accuracy: 22.5%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Minibatch loss at step 445: 2148.631836
Minibatch accuracy: 66.0%
[[

Minibatch loss at step 484: 8630.684570
Minibatch accuracy: 77.5%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 485: 5576.288574
Minibatch accuracy: 74.9%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 486: 5371.081055
Minibatch accuracy: 62.7%
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 1.]
 [1. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 487: 6673.819336
Minibatch accuracy: 63.4%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 488: 1054.195068
Minibatch accuracy: 79.4%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 489: 1653.529907
Minibatch accuracy: 78.2%
[[1.

Minibatch loss at step 528: 17834.939453
Minibatch accuracy: 65.3%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 529: 18182.000000
Minibatch accuracy: 65.1%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 530: 12545.274414
Minibatch accuracy: 66.4%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 531: 4104.804199
Minibatch accuracy: 21.8%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Minibatch loss at step 532: 6938.548340
Minibatch accuracy: 75.9%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 533: 12075.635742
Minibatch accuracy: 77.3%


Minibatch loss at step 573: 3019.726562
Minibatch accuracy: 64.7%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 574: 2975.030273
Minibatch accuracy: 77.3%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 575: 5474.249023
Minibatch accuracy: 74.7%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 576: 4849.823242
Minibatch accuracy: 77.5%
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 577: 4646.082520
Minibatch accuracy: 33.9%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
Minibatch loss at step 578: 959.395081
Minibatch accuracy: 76.4%
[[0. 

Minibatch loss at step 618: 7146.802734
Minibatch accuracy: 77.4%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 619: 4158.035156
Minibatch accuracy: 77.3%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 620: 965.458862
Minibatch accuracy: 65.9%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 621: 3367.833496
Minibatch accuracy: 64.8%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 622: 1938.894775
Minibatch accuracy: 67.2%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 623: 1477.660156
Minibatch accuracy: 78.0%
[[1. 

Minibatch loss at step 663: 326.359528
Minibatch accuracy: 76.5%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 664: 914.670410
Minibatch accuracy: 65.1%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 665: 866.661377
Minibatch accuracy: 75.4%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 666: 637.135437
Minibatch accuracy: 77.7%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 667: 1581.312256
Minibatch accuracy: 66.6%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 668: 835.806519
Minibatch accuracy: 63.6%
[[1. 0.]


Minibatch loss at step 708: 11326.985352
Minibatch accuracy: 78.2%
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 709: 13524.099609
Minibatch accuracy: 76.8%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 710: 13345.069336
Minibatch accuracy: 77.1%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 711: 12106.380859
Minibatch accuracy: 77.8%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 712: 11184.191406
Minibatch accuracy: 76.0%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 713: 7671.469727
Minibatch accuracy: 78.5%

Minibatch loss at step 753: 725.982971
Minibatch accuracy: 77.3%
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 754: 1030.033569
Minibatch accuracy: 76.3%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 755: 757.158081
Minibatch accuracy: 76.2%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 756: 73.472763
Minibatch accuracy: 64.8%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 757: 169.867386
Minibatch accuracy: 75.1%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 758: 382.268097
Minibatch accuracy: 22.2%
[[1. 1.]
 

Minibatch loss at step 798: 1566.808105
Minibatch accuracy: 32.4%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Minibatch loss at step 799: 2038.962280
Minibatch accuracy: 70.2%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 800: 1081.469604
Minibatch accuracy: 69.2%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 801: 680.820007
Minibatch accuracy: 76.6%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 802: 1448.749023
Minibatch accuracy: 76.4%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 803: 1457.749390
Minibatch accuracy: 79.0%
[[1. 

Minibatch loss at step 843: 1342.726196
Minibatch accuracy: 64.5%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 844: 559.804321
Minibatch accuracy: 24.2%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Minibatch loss at step 845: 523.010437
Minibatch accuracy: 35.7%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
Minibatch loss at step 846: 979.324707
Minibatch accuracy: 76.8%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 847: 417.116608
Minibatch accuracy: 75.9%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 848: 3349.942627
Minibatch accuracy: 22.1%
[[1. 1.]

Minibatch loss at step 888: 1063.992920
Minibatch accuracy: 55.1%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 889: 539.702576
Minibatch accuracy: 49.7%
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 890: 598.727783
Minibatch accuracy: 88.2%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 891: 1198.189575
Minibatch accuracy: 73.0%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 892: 6742.680176
Minibatch accuracy: 50.0%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 893: 6189.633789
Minibatch accuracy: 50.0%
[[0. 1

Minibatch loss at step 933: 1940.360840
Minibatch accuracy: 64.6%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 934: 966.877502
Minibatch accuracy: 67.0%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 935: 1053.347900
Minibatch accuracy: 77.8%
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 936: 1586.497192
Minibatch accuracy: 76.3%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 937: 1861.954346
Minibatch accuracy: 76.7%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 938: 1826.183350
Minibatch accuracy: 77.4%
[[1. 

Minibatch loss at step 978: 112.525688
Minibatch accuracy: 77.5%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 979: 146.186371
Minibatch accuracy: 74.8%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 980: 62.307514
Minibatch accuracy: 77.3%
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Minibatch loss at step 981: 301.918945
Minibatch accuracy: 65.1%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 982: 291.638611
Minibatch accuracy: 62.7%
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch loss at step 983: 91.009552
Minibatch accuracy: 78.1%
[[0. 1.]
 [0

160110 166040
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch accuracy: 65.3%
166040 171970
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch accuracy: 65.4%
171970 177900
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch accuracy: 66.2%
177900 183830
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch accuracy: 64.8%
183830 189760
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch accuracy: 67.2%
189760 195690
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch accuracy: 64.5%
195690 201620
[[1. 1.]
 [1. 1.]
 [1. 1.]

468470 474400
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch accuracy: 64.8%
474400 480330
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch accuracy: 64.2%
480330 486260
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch accuracy: 66.1%
486260 492190
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch accuracy: 63.8%
492190 498120
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch accuracy: 65.9%
498120 504050
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch accuracy: 64.0%
504050 509980
[[1. 1.]
 [1. 1.]
 [1. 1.]

In [46]:
533772+59308

593080

In [62]:
train_label_hot.shape

(593089, 2)

In [46]:
predictions

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [52]:
batch_labels.shape

(5930, 2)

In [55]:
predictions[:3].shape

(3, 2)

In [63]:
(np.sum(predictions == batch_labels))/num_label/predictions.shape[0]

0.18591905564924116

Small NN

In [68]:
batch_size = int(num_samples/100)
hidden_size = 4
hidden_size2 = 4
hidden_size3 = 4
hidden_size4 = 4

# 20, 100, 500, 1000, 2000

# graph = tf.Graph()
# with tf.device('/device:GPU:0'):
# with graph.as_default():
# Input data. For the training data, we use a placeholder that will be fed
# at run time with a training minibatch.
tf_train_dataset = tf.placeholder(tf.float32, shape=(batch_size, 1))
tf_train_labels = tf.placeholder(tf.float32, shape=(batch_size, num_label))
# tf_valid_dataset = tf.constant(valid_dataset)
tf_test_dataset = tf.placeholder(tf.float32, shape=(batch_size, num_label))
tf_test_labels = tf.placeholder(tf.float32, shape=(batch_size, num_label))

# Variables.
weights1 = tf.Variable(tf.truncated_normal([1, hidden_size]))
biases1 = tf.Variable(tf.zeros([hidden_size]))

weights2 = tf.Variable(tf.truncated_normal([hidden_size, num_label]))
biases2 = tf.Variable(tf.zeros([num_label]))

"""
weights2 = tf.Variable(tf.truncated_normal([hidden_size, hidden_size2]))
biases2 = tf.Variable(tf.zeros([hidden_size2]))

weights3 = tf.Variable(tf.truncated_normal([hidden_size2,  num_label]))
biases3 = tf.Variable(tf.zeros([ num_label]))


# weights4 = tf.Variable(tf.truncated_normal([hidden_size3, num_label]))
# biases4 = tf.Variable(tf.zeros([num_label]))
weights4 = tf.Variable(tf.truncated_normal([hidden_size3, hidden_size4]))
biases4 = tf.Variable(tf.zeros([hidden_size4]))

weights5 = tf.Variable(tf.truncated_normal([hidden_size4, num_label]))
biases5 = tf.Variable(tf.zeros([num_label]))
"""

# Training computation.
logits1 = tf.matmul(tf_train_dataset, weights1) + biases1  
relu_act_func = tf.nn.relu(logits1)
logits2 = tf.matmul(relu_act_func, weights2) + biases2

"""
relu_act_func2 = tf.nn.relu(logits2)
logits3 = tf.matmul(relu_act_func2, weights3) + biases3

relu_act_func3 = tf.nn.relu(logits3)
logits4 = tf.matmul(relu_act_func3, weights4) + biases4

relu_act_func4 = tf.nn.relu(logits4)
logits5 = tf.matmul(relu_act_func4, weights5) + biases5
"""

logits = logits2

# loss calculation
# loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=tf_train_labels, logits=logits5))
loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(labels=tf_train_labels, logits=logits))

# Predictions for the training, validation, and test data.
# train_prediction = tf.nn.softmax(logits5)
train_prediction = tf.round(tf.sigmoid(logits))

# loss = tf.reduce_mean(tf.losses.absolute_difference(labels=tf_train_labels, predictions=train_prediction))

loss_summary = tf.summary.scalar('loss', loss)

# Optimizer.
# optimizer = tf.train.GradientDescentOptimizer(0.0001).minimize(loss)
optimizer = tf.train.AdamOptimizer(2).minimize(loss)

In [69]:
num_steps = int(iteration_one_epoch*10)
loss_history = []

with tf.Session() as session:
# with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as session:
#with tf.Session(graph=graph) as session:
    tf.global_variables_initializer().run()
    print("Initialized")
    for step in range(num_steps):
        # Pick an offset within the training data, which has been randomized.
        # Note: we could use better randomization across epochs.
        offset = (step * batch_size) % (train_label_hot.shape[0] - batch_size)
        # Generate a minibatch.
        batch_data = train_dataset_reform[offset:(offset + batch_size), :]
        batch_labels = train_label_hot[offset:(offset + batch_size), :]

        # print(offset)
        # Prepare a dictionary telling the session where to feed the minibatch.
        # The key of the dictionary is the placeholder node of the graph to be fed,
        # and the value is the numpy array to feed to it.
        feed_dict = {tf_train_dataset : batch_data, tf_train_labels : batch_labels}
        _, l, predictions, added_summary, logits_check = session.run(
            [optimizer, loss, train_prediction, loss_summary, logits], feed_dict=feed_dict)

        # writer.add_summary(added_summary)
        loss_history.append(l)
        # print(offset, batch_size)
        print("Minibatch loss at step %d: %f" % (step, l))
        print("Minibatch accuracy: %.1f%%" % accuracy(predictions, batch_labels))
        print(batch_labels)
        print(predictions)
        print(weights1.eval())
        # if (step % iteration_one_epoch == 0):
        # print("Minibatch loss at step %d: %f" % (step, l))
            # print("Minibatch accuracy: %.1f%%" % accuracy(predictions, batch_labels))
            # print(logits_check)
            # print(weights1.eval())
            # print("Validation accuracy: %.1f%%" % accuracy(valid_prediction.eval(), valid_labels))
    
    # Do for the test batch
    acc = 0
    for step in range(int(iteration_one_epoch)):
        # Pick an offset within the training data, which has been randomized.
        # Note: we could use better randomization across epochs.
        offset = (step * batch_size) % (train_label_hot.shape[0] - batch_size)
        # Generate a minibatch.
        batch_data = train_dataset_reform[offset:(offset + batch_size), :]
        batch_labels = train_label_hot[offset:(offset + batch_size), :]

        # print(offset)
        # Prepare a dictionary telling the session where to feed the minibatch.
        # The key of the dictionary is the placeholder node of the graph to be fed,
        # and the value is the numpy array to feed to it.
        feed_dict = {tf_train_dataset : batch_data, tf_train_labels : batch_labels}
        loss_test, test_predictions = session.run([loss, train_prediction], feed_dict=feed_dict)
        print(step, offset, offset + batch_size, loss_test)
        print(batch_labels)
        print(test_predictions)
        batch_acc = accuracy(test_predictions, batch_labels)
        print("Minibatch accuracy: %.1f%%" % batch_acc)
        acc = acc + batch_acc

    print(acc)
        

Initialized
Minibatch loss at step 0: 1720.878418
Minibatch accuracy: 50.0%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[-0.96173817 -0.80049795  2.1028476  -1.4732914 ]]
Minibatch loss at step 1: 0.000000
Minibatch accuracy: 100.0%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[-0.96173817 -0.80049795  3.4429598  -2.8134031 ]]
Minibatch loss at step 2: 0.000000
Minibatch accuracy: 100.0%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[-0.96173817 -0.80049795  4.4788666  -3.84931   ]]
Minibatch loss at step 3: 0.000000
Minibatch accuracy: 100.0%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[-0.96173817 -0.80049795  5.3274217  -4.697865  ]]
Minibatch loss at step 4: 0.000000
Minibatch accur

Minibatch loss at step 37: 0.462261
Minibatch accuracy: 78.2%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -15.384248   -11.227346  ]]
Minibatch loss at step 38: 0.468001
Minibatch accuracy: 76.1%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -15.499875   -11.250741  ]]
Minibatch loss at step 39: 0.478378
Minibatch accuracy: 77.1%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -15.605117   -11.272034  ]]
Minibatch loss at step 40: 0.472071
Minibatch accuracy: 77.1%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -15.7008915  -11.291411  ]]
Minibatch loss at step 41: 0.498957
Minibatch ac

Minibatch loss at step 86: 0.497677
Minibatch accuracy: 75.1%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.643785   -11.4821825 ]]
Minibatch loss at step 87: 0.475460
Minibatch accuracy: 77.5%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.644775   -11.482383  ]]
Minibatch loss at step 88: 0.490573
Minibatch accuracy: 74.8%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.645672   -11.482564  ]]
Minibatch loss at step 89: 0.485454
Minibatch accuracy: 77.4%
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.646484   -11.482728  ]]
Minibatch loss at step 90: 0.497083
Minibatch ac

[[ -0.96173817  -0.80049795 -16.654108   -11.48427   ]]
Minibatch loss at step 134: 0.563116
Minibatch accuracy: 78.2%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654118   -11.484272  ]]
Minibatch loss at step 135: 0.632938
Minibatch accuracy: 75.8%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654125   -11.484274  ]]
Minibatch loss at step 136: 0.592046
Minibatch accuracy: 77.4%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654133   -11.484276  ]]
Minibatch loss at step 137: 0.556539
Minibatch accuracy: 76.8%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654139   -11

Minibatch loss at step 180: 0.484361
Minibatch accuracy: 75.3%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 181: 0.489912
Minibatch accuracy: 76.6%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 182: 0.479742
Minibatch accuracy: 76.3%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 183: 0.495266
Minibatch accuracy: 75.5%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 184: 0.476966
Minibat

Minibatch accuracy: 66.7%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 228: 0.598336
Minibatch accuracy: 64.9%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 229: 0.499065
Minibatch accuracy: 65.7%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 230: 0.487854
Minibatch accuracy: 76.1%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 231: 0.484589
Minibatch accuracy: 78.2%
[[1. 1.]
 [1. 1.]


Minibatch accuracy: 75.8%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 273: 0.488779
Minibatch accuracy: 76.3%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 274: 0.475240
Minibatch accuracy: 76.9%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 275: 0.495177
Minibatch accuracy: 75.2%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 276: 0.472375
Minibatch accuracy: 77.6%
[[1. 1.]
 [1. 1.]


[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 321: 0.489223
Minibatch accuracy: 77.9%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 322: 0.511396
Minibatch accuracy: 75.7%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 323: 0.605600
Minibatch accuracy: 64.8%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 324: 0.661231
Minibatch accuracy: 67.1%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11

[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 369: 0.480246
Minibatch accuracy: 75.6%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 370: 0.489320
Minibatch accuracy: 76.6%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 371: 0.477774
Minibatch accuracy: 76.6%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 372: 0.491930
Minibatch accuracy: 75.5%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11

Minibatch loss at step 415: 0.992378
Minibatch accuracy: 78.3%
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 416: 1.002398
Minibatch accuracy: 76.6%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 417: 0.875038
Minibatch accuracy: 77.1%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 418: 0.721461
Minibatch accuracy: 77.6%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 419: 0.619301
Minibat

Minibatch loss at step 456: 0.475245
Minibatch accuracy: 76.9%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 457: 0.487103
Minibatch accuracy: 75.6%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 458: 0.466488
Minibatch accuracy: 77.8%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 459: 0.487489
Minibatch accuracy: 75.1%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 460: 0.478899
Minibat

Minibatch loss at step 504: 1.704640
Minibatch accuracy: 68.4%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 505: 1.627023
Minibatch accuracy: 67.8%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 506: 1.365231
Minibatch accuracy: 68.2%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 507: 1.195352
Minibatch accuracy: 64.7%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 508: 0.765834
Minibat

[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 553: 0.483224
Minibatch accuracy: 76.6%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 554: 0.492374
Minibatch accuracy: 76.0%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 555: 0.473338
Minibatch accuracy: 77.7%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 556: 0.487110
Minibatch accuracy: 75.0%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11

[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 602: 1.662874
Minibatch accuracy: 68.8%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 603: 1.712386
Minibatch accuracy: 68.3%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 604: 1.617936
Minibatch accuracy: 68.1%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 605: 1.403280
Minibatch accuracy: 67.4%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11

Minibatch loss at step 646: 0.505423
Minibatch accuracy: 75.7%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 647: 0.466587
Minibatch accuracy: 78.0%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 648: 0.480002
Minibatch accuracy: 75.3%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [1. 0.]
 [1. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 649: 0.478169
Minibatch accuracy: 77.4%
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 650: 0.476085
Minibat

Minibatch accuracy: 83.0%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 690: 0.455934
Minibatch accuracy: 82.7%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 691: 0.399232
Minibatch accuracy: 87.1%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 692: 0.380475
Minibatch accuracy: 88.0%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 693: 0.650022
Minibatch accuracy: 71.7%
[[1. 0.]
 [1. 0.]


[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 735: 0.503189
Minibatch accuracy: 66.0%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 736: 0.525385
Minibatch accuracy: 65.2%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 737: 0.512521
Minibatch accuracy: 65.0%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 738: 0.502961
Minibatch accuracy: 66.2%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11

Minibatch loss at step 781: 0.495542
Minibatch accuracy: 75.6%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 782: 0.477299
Minibatch accuracy: 77.2%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 783: 0.495599
Minibatch accuracy: 75.8%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 784: 0.486743
Minibatch accuracy: 76.8%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 785: 0.481170
Minibat

[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 826: 0.548272
Minibatch accuracy: 77.2%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 827: 0.562805
Minibatch accuracy: 77.2%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 828: 0.591596
Minibatch accuracy: 76.1%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 829: 0.527259
Minibatch accuracy: 78.2%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11

[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 873: 0.496097
Minibatch accuracy: 75.3%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 874: 0.473637
Minibatch accuracy: 77.5%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 875: 0.488327
Minibatch accuracy: 74.8%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 876: 0.486737
Minibatch accuracy: 77.0%
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11

Minibatch loss at step 916: 0.513500
Minibatch accuracy: 78.0%
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 917: 0.554090
Minibatch accuracy: 66.5%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 918: 0.645995
Minibatch accuracy: 65.3%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 919: 0.684218
Minibatch accuracy: 65.4%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 920: 0.662568
Minibat

Minibatch accuracy: 77.1%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 962: 0.478292
Minibatch accuracy: 76.2%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 963: 0.490621
Minibatch accuracy: 76.0%
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 964: 0.475883
Minibatch accuracy: 77.2%
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[ -0.96173817  -0.80049795 -16.654194   -11.484285  ]]
Minibatch loss at step 965: 0.494707
Minibatch accuracy: 74.9%
[[0. 1.]
 [0. 1.]


4 23720 29650 0.0039806594
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch accuracy: 100.0%
5 29650 35580 0.0039806594
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch accuracy: 100.0%
6 35580 41510 1.2076807
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch accuracy: 76.2%
7 41510 47440 1.5375363
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch accuracy: 70.1%
8 47440 53370 1.5679694
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch accuracy: 69.3%
9 53370 59300 1.6407044
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]

54 320220 326150 1.8299862
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch accuracy: 64.8%
55 326150 332080 1.7816178
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch accuracy: 66.1%
56 332080 338010 1.8489889
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch accuracy: 64.4%
57 338010 343940 1.7449518
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch accuracy: 66.5%
58 343940 349870 1.8742738
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Minibatch accuracy: 64.2%
59 349870 355800 1.7984915
[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.

In [246]:
#BATCH

In [ ]:
batch_size = int(num_samples)
hidden_size = 1024
hidden_size2 = 512
hidden_size3 = 16

# 20, 100, 500, 1000, 2000

# graph = tf.Graph()

#with graph.as_default():
# Input data. For the training data, we use a placeholder that will be fed
# at run time with a training minibatch.
tf_train_dataset = tf.placeholder(tf.float32, shape=(batch_size, 1))
tf_train_labels = tf.placeholder(tf.float32, shape=(batch_size, num_label))
# tf_valid_dataset = tf.constant(valid_dataset)
# tf_test_dataset = tf.constant(test_dataset)

# Variables.
weights1 = tf.Variable(tf.truncated_normal([1, hidden_size]))
biases1 = tf.Variable(tf.zeros([hidden_size]))

weights2 = tf.Variable(tf.truncated_normal([hidden_size, hidden_size2]))
# biases2 = tf.Variable(tf.zeros([num_label]))
biases2 = tf.Variable(tf.zeros([hidden_size2]))

weights3 = tf.Variable(tf.truncated_normal([hidden_size2, hidden_size3]))
biases3 = tf.Variable(tf.zeros([hidden_size3]))

weights4 = tf.Variable(tf.truncated_normal([hidden_size3, num_label]))
biases4 = tf.Variable(tf.zeros([num_label]))

# Training computation.
logits1 = tf.matmul(tf_train_dataset, weights1) + biases1  
relu_act_func = tf.nn.relu(logits1)
logits2 = tf.matmul(relu_act_func, weights2) + biases2

relu_act_func2 = tf.nn.relu(logits2)
logits3 = tf.matmul(relu_act_func2, weights3) + biases3

relu_act_func3 = tf.nn.relu(logits3)
logits4 = tf.matmul(relu_act_func3, weights4) + biases4

loss = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits_v2(labels=tf_train_labels, logits=logits4))

# Predictions for the training, validation, and test data.
train_prediction = tf.nn.softmax(logits4)

# loss = tf.reduce_mean(tf.losses.absolute_difference(labels=tf_train_labels, predictions=train_prediction))

loss_summary = tf.summary.scalar('loss', loss)

# Optimizer.
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(loss)
#optimizer = tf.train.AdamOptimizer(1).minimize(loss)

# Predictions for the training, validation, and test data.
# train_prediction = tf.nn.softmax(logits4)

#valid_prediction = tf.nn.softmax(
#    tf.matmul(tf.nn.relu(tf.matmul(tf_valid_dataset, weights1) + biases1), weights2) + biases2)
#test_prediction = tf.nn.softmax(
#    tf.matmul(tf.nn.relu(tf.matmul(tf_test_dataset, weights1) + biases1), weights2) + biases2)

writer = tf.summary.FileWriter('./vehicle', tf.get_default_graph())

In [ ]:
# BATCH GRADIENT DESCENT
loss_history = []
num_steps = 2

with tf.Session() as session:
#with tf.Session(graph=graph) as session:
  tf.global_variables_initializer().run()
  print("Initialized")
  for step in range(num_steps):
    # Pick an offset within the training data, which has been randomized.
    # Note: we could use better randomization across epochs.
    #offset = (step * batch_size) % (train_label_hot.shape[0] - batch_size)
    # Generate a minibatch.
    #batch_data = train_dataset_reform[offset:(offset + batch_size), :]
    #batch_labels = train_label_hot[offset:(offset + batch_size), :]
    batch_data = train_dataset_reform
    batch_labels = train_label_hot
    
    # Prepare a dictionary telling the session where to feed the minibatch.
    # The key of the dictionary is the placeholder node of the graph to be fed,
    # and the value is the numpy array to feed to it.
    feed_dict = {tf_train_dataset : batch_data, tf_train_labels : batch_labels}
    _, l, predictions, added_summary = session.run(
        [optimizer, loss, train_prediction, loss_summary], feed_dict=feed_dict)
    
    writer.add_summary(added_summary)
    loss_history.append(l)
    
    # if (step % iteration_one_epoch == 0):
    print("Minibatch loss at step %d: %f" % (step, l))
    print("Minibatch accuracy: %.1f%%" % accuracy(predictions, batch_labels))
    # print("Validation accuracy: %.1f%%" % accuracy(valid_prediction.eval(), valid_labels))
    # print("Test accuracy: %.1f%%" % accuracy(test_prediction.eval(), test_labels))